### ISSUE TITLE
RFC-2: PREIMAGE-SHA-256 and OP_HASH256

### ISSUE THREAD

**Issue by nbougalis** [interledger/rfcs#108]
In Section 4.1 of the RFC, when describing `PREIMAGE-SHA-256`, the following sentence is present:

> Bitcoin supports this type of condition via the `OP_HASH256` operator.

This is not accurate. Our `PREIMAGE-SHA-256` operation performs a single SHA-256 operation. That is, a fulfillment `f` has a preimage `p`, and the condition contains `SHA256(p)` instead of `SHA256(SHA256(p))`.

In order to get `OP_HASH256` semantics for a given preimage `p`, the caller must create a fulfillment that contains `SHA256(p)`. We should either remove the wording, modify it to explain the difference and how one must go about getting `OP_HASH256` semantics, or modify `PREIMAGE-SHA-256`.

I may be in the minority here, but I believe that we should consider the third option: modifying. Here's what I would do:

Given a message `m`, define the fulfillment payload for PREIMAGE-SHA-256 fulfillment to be `SHA256(m)`. The condition remains unchanged - it's payload will now be `SHA256(SHA256(m))`.

Note that the fulfillment `f` alone is sufficient when verifying that it matches a given condition `c`. The message `m` isn't needed. Thinking of cryptoconditions as curried functions, preimage changes from this:

```
preimageSha256(hash)(preimage)()
```
to this:
```
preimageSha256(hash)(preimage)(message)
```

This also means that preimage fulfillments are compact. Under the current standard and with existing implementations, a fulfillment's payload could be 64k.

I do not believe that this modification gives up any functionality nor does it changes the security model in any way.

**Comment by justmoon** [comment]
We've been thinking of preimage conditions as a binary input to a condition tree. Either you have the preimage (true) or you don't (false). This is useful as a way to "lock" or "turn off" branches of a threshold tree.

Suppose you have a key A - and you want that key to be able to sign things, but only after another system  has revealed a secret B to unlock it.

You'd have THRESHOLD(2, ED25519(A), PREIMAGE(B))

If the preimage depended on a specific message, this wouldn't be possible.

A use case would be: Imagine a company has an "emergency committee" which has its own set of keys, but those should only be usable after the CEO has declared an emergency.

```
OR(
  [regular day-to-day keys],
  AND(
    [emergency keys],
    PREIMAGE(ceo_state_of_emergency_code)
  )
)
```

> This also means that preimage fulfillments are compact. Under the current standard and with existing implementations, a fulfillment's payload could be 64k.

Nobody is forcing you to choose a certain preimage. If you want to use SHA256(64k thing) as the preimage you can already do that.

> > Bitcoin supports this type of condition via the OP_HASH256 operator.
> This is not accurate.

True, that should be fixed in the documentation.
