### ISSUE TITLE
RFC9: What is SPSP?

### ISSUE THREAD

**Issue by sharafian** [interledger/rfcs#152]
Right now, the version of SPSP [in the RFCS](https://github.com/interledger/rfcs/blob/master/0009-simple-payment-setup-protocol/0009-simple-payment-setup-protocol.md) isn't the same as the version of SPSP being used in production (in the ILP-Kit).

The ILP Kit's implementation rolls the query step and the optional webfinger lookup into an HTTP get that returns the query information as a webfinger resource.

We should have a discussion over what SPSP should look like.

## Open Questions

0. How should the SPSP methods be divided up?
0. How should invoices work?
0. What HTTP method should setup be?
0. Can you query with a URL instead of a webfinger `acct`?
0. Should SPSP use [SSP](https://github.com/interledger/rfcs/issues/43#issuecomment-274274862) or [IPR](https://github.com/interledger/rfcs/blob/master/0011-interledger-payment-request/0011-interledger-payment-request.md)?

## Use Case

SPSP is for the case where:

0. The sender and receiver don't have a pre-established data channel.
0. The receiver has an HTTP server or has an HTTP server acting on their behalf.
0. The receiver wants to accept exactly one payment.
0. One or two HTTP round trips per payment are acceptable.

From an architectural point of view:

0. The receiver wants to perform logic at setup-time, not at fulfill-time.
0. The receiver wants to accept payments in a stateless way.
0. The HTTP server that gives out IPR packets has the same HMAC key as the receivers that fulfill payments, but the HTTP server doesn't necessarily have ledger credentials.
0. The client doesn't need any crypto libraries (for IPR).

# Proposal

## SPSP flow (from the client's point of view)

I've chosen to split the SPSP flow into two phases.
Whether an API chooses to split the flow up into these two phases is an implementation detail.

### Quote-Query Phase

0. GET webfinger endpoint corresponding to receiver (`alice@example.com` -> `https://example.com/.well-known/webfinger?resource=acct:alice@example.com`, OR `https://example.com/receiverid/12414` -> `https://example.com/.well-known/webfinger?resource=https://example.com/receiverid/12414`)
0. (If source-amount quoted) Using the ILP address from query result, make an ILQP quote to get destination amount.
0. (If dest-amount quoted) Using the ILP address from query result, make an ILQP quote to get source amount.

Now you have all the information required to set up and send the payment. A client implementation could represent this as a quote-query object that can be validated by client-side logic. A uuid on the quote-query object could make the send-setup phase idempotent.

### Send-Setup Phase

0. GET (POST?) to setup endpoint using destination amount from quote-query phase.
0. If the IPR packet's destination amount differs from the destination amount in your quote-query object, throw an error.
0. Send a payment using the IPR payment in accordance with the IPR protocol. Send your transfer with the source amount you had in your quote-query step.

### Query

The query stage is a GET call to the `/.well-known/webfinger?resource=...` endpoint on a domain.
It returns a webfinger resource, with the following fields (it may contain additional fields):

```js
{
  "subject": "acct:alice@example.com",
  "links": [
    {
      "rel": "https://interledger.org/rel/ilpAddress",
      "href": "example.alice."
    },
    {
      "rel": "https://interledger.org/rel/receiver",
      "href": "https://example.com/api/receivers/alice"
    }
  ]
}
```

A possible way to implement invoices would be to include an 'amount' field when the resource is an invoice. If client tries to specify a source/destination amount in the quote-query phase, and they get back an amount in the query, they should get an error. Similarly, if the client doesn't specify an amount in the quote-query phase, and the query response doesn't include an amount, this should cause an error.

### Setup

The setup stage is a GET call to the link with `"rel": "https://interledger.org/rel/receiver"`.
This endpoint should be called with an `amount`, which is the destination amount for the receiving account. The returned object should be an IPR packet. Refer to the [IPR spec](https://github.com/interledger/rfcs/blob/master/0011-interledger-payment-request/0011-interledger-payment-request.md) for the format.

**Comment by justmoon** [comment]
We should consider switching SPSP to SSP, which would eliminate the Setup stage, saving us a roundtrip and allowing multiple consecutive payments without querying the receiver again.

The other main question is whether the webfinger and query stages should be combined. I think there are use cases where I would want a static webfinger resource hosted on my main webserver which is merely pointing to the real SPSP receiver. E.g. my ILP Kit is running at `nexus.justmoon.com`, but I want addresses like `bob@justmoon.com`, so I put a static webfinger file at `https://justmoon.com/.well-known/webfinger`.

This could also be achieved using a redirect, which webfinger explicitly allows.

Right now I'm leaning towards just having a webfinger lookup, which points to an SPSP receiver endpoint. That way discovery (i.e. DNS) and the application layer protocol (i.e. HTTP) are cleanly separated.

**Comment by sharafian** [comment]
Would a redirect cause it to query `https://nexus.justmoon.com/.well-known/webfinger?resource=acct:bob@justmoon.com` instead of `https://nexus.justmoon.com/.well-known/webfinger?resource=acct:bob@nexus.justmoon.com`?

**Comment by justmoon** [comment]
> Wouldn't a redirect cause it to query https://nexus.justmoon.com/.well-known/webfinger?resource=acct:bob@justmoon.com instead of https://nexus.justmoon.com/.well-known/webfinger?resource=acct:bob@nexus.justmoon.com?

Yes, we'd either ignore the hostname or add an `API_ALTERNATE_HOSTNAMES` config parameter.

> Regarding IPR vs. SSP, an extra HTTP round trip isn't very cumbersome for most situations. I like SSP for its flexibility to allow more complex applications on top of it, but I'm not totally sure it's worth the added complexity in the one-payment use case.

You're saying you're not sure whether saving a roundtrip is "worth the extra complexity" of SSP. But the fact that SSP has one less round trip is exactly what makes it simpler than IPR imho.

The difference between SSP and IPR, in essence, is that in SSP both sender and receiver know the secret, whereas in IPR only the receiver knows the secret. Otherwise, they both work more or less the same.

From that difference arise some tradeoffs. SSP allows the sender to make payments non-interactively, so it doesn't require the sender to "request a payment request", it can just create the condition locally. So in many cases, it will save a round trip (like in SPSP) or even multiple roundtrips (like if you're doing streaming or multiple payments). In short, SSP is more general. With IPR on the other hand, only the receiver can create payment requests, which creates the potential for non-repudiability.

So I think you'd use SSP most of the time and if you needed non-repudiability, you'd use IPR, unless I'm missing something.

**Comment by emschwartz** [comment]
I agree that SSP is preferable for streaming, but I don't think that's the use case for SPSP.

To me "Simple Payment Setup" means a single flow to set up a single payment. I don't want to get a key that I can use to send multiple payments, I want to do one payment. I think this is a common enough use case that it's fine to have a protocol for this flow.

I would advocate for separately defining SSP and using it for most of our streaming applications.

**Comment by sharafian** [comment]
I think it also depends whether non-repudiability is something we want most of the time.

It could be a liability to a receiver if senders can send payments without authorization. For example, a client might experience an error and send funds twice on an SSP connection instead of once. Then it's up to the receiver to figure out how to set things.

**Comment by justmoon** [comment]
> I think it also depends whether non-repudiability is something we want most of the time.

To add non-repudiability in SPSP, using IPR would only be one small piece of the puzzle. The more difficult part would be to create a signed invoice tying the condition to the receiver's real-world identity. The best option for that would probably be to use the receiver's SSL certificate. If it's an SSL EV certificate, it would be tied to a real-world person or organization. So we would sign the Setup response using something like JWS.

I think this *could* be part of SPSP if there was demand, but since it would depend on asymmetric crypto, it would probably make the spec quite a bit more complex (or add a dependency on another large, complex spec, like JWS.) So my recommendation would be to leave it out as it's clearly not necessary for an MVP.

> It could be a liability to a receiver if senders can send payments without authorization. For example, a client might experience an error and send funds twice on an SSP connection instead of once. Then it's up to the receiver to figure out how to set things.

How is that not also a problem with IPR? I can pay using the same request twice and it's up to the receiver to reject it the second time.

---

For anyone reading along - @emschwartz, @sharafian and I discussed this on a call which @sharafian summarized with the following proposal: https://gist.github.com/sharafian/df7a4b7e2ff000248800b113f06f549a

**Comment by adrianhopebailie** [comment]
Q: Are we changing SPSP or inventing a new (possibly better) protocol and wanting to steal the name SPSP?

i.e. Does this proposal make IPR redundant? Do we have a new name for the protocol we currently call SPSP or is it just the deprecated v1 of SPSP?

**Comment by emschwartz** [comment]
I think the idea is to deprecate SPSP v1 and just call this new and improved protocol "SPSP". SPSP is not widely deployed right now outside of our components so I don't think that's much of an issue. The new version is meant to address a number of issues with the original SPSP that we found over the course of a couple months of using it.

**Comment by adrianhopebailie** [comment]
Okay, so is RFC 11 (IPRs) redundant (for now)?

**Comment by emschwartz** [comment]
I wouldn't say it's redundant but the current plan is to switch from IPR to SSP/KEP in most of our current use cases.

**Comment by adrianhopebailie** [comment]
If we don't have an actual use for an IPR then I would say it's redundant 😄 
But that is useful in discussing the proposal.

Have made a [comment](https://gist.github.com/sharafian/df7a4b7e2ff000248800b113f06f549a#gistcomment-1989619) on @sharafian 's proposal in light of that.

**Comment by emschwartz** [comment]
@justmoon I like the idea of combining the webfinger and query steps into one call that uses `/.well-known/spsp`. It seems silly to define a protocol that uses webfinger, only to get a URL you're going to turn around and query right away.

I'm not a fan of @adrianhopebailie's idea of including multiple invoices in the response. Since this protocol is about setting up a payment, I don't see any reason to have more than one thing come back. If you want to send someone multiple invoices, you can use a different SPSP identifier for each.

As far as format goes, I would propose:

``` json
{
  "shared_secret": "itsasecret",
  "destination_account": "someledger.merchant.111-7777777-1111111",
  "maximum_destination_amount": "10.40",
  "minimum_destination_amount": "10.40",
  "receiver_info": {
    "name": "Amazon S.A.",
    "type": "invoice",
    "currency_code": "USD",
    "currency_symbol": "$",
    "amount_scale": "4",
    "amount_precision": "10",
    "info_url": "https://www.amazon.com/gp/your-account/order-details?ie=UTF8&orderID=111-7777777-1111111",
    "image_url": "https://amazon.com/images/logo.png"
  }
}
```
The top-level fields are required to actually set up the payment, and the things under `receiver_info` are for display purposes. We should define as many fields as we think people might want to put in here, so the sending side knows what to look for, but none of them are required.

**Comment by adrianhopebailie** [comment]
>I like the idea of combining the webfinger and query steps into one call that uses /.well-known/spsp. It seems silly to define a protocol that uses webfinger, only to get a URL you're going to turn around and query right away.

Nooo! Don't use `.well-known` addresses for things they aren't intended for. They're supposed to return "host level" information. 

I guess we could define a new `.well-known` namespace as an **alternative** to the WebFinger discovery step which gives you a shortcut from knowing the `account@host` identifier to having all the info you need to send the payment but we still need a way for a receiver to provide a URL (that is not always as a `.well-known` base) to senders so that the sender can get the setup info.

i.e. Discovery and query are necessarily different things. We can define a protocol that combines them for efficiency but we shouldn't forgo having a stand alone query protocol.

> I'm not a fan of @adrianhopebailie's idea of including multiple invoices in the response. **Since this protocol is about setting up a payment**

Exactly. A payment is not the same thing as an invoice. Let's not confuse a "request to be paid a fixed amount for a specific thing" with an invoice.

It's very common, I do it every month, to make a single payment that pays the amount owed on multiple invoices.

If we don't want to worry about all the use cases involved in invoicing then let's just take the concept of "invoice" right out and just have a "payment reference" that the sender can provide that allows the receiver to specify a predetermined amount. If the receiver ties that to an invoice in the background that's fine.

We're also conflating a receiver "Amazon", with an invoice. We should take that out

**Comment by emschwartz** [comment]
> I guess we could define a new .well-known namespace as an alternative to the WebFinger discovery step which gives you a shortcut from knowing the account@host identifier to having all the info you need to send the payment

Yeah that's exactly what I mean. We would define the SPSP protocol to say you translate `justmoon@nexus.justmoon.com` into `GET https://justmoon.com/.well-known/spsp?destination_identifier=justmoon@nexus.justmoon.com` or something like that. The result would be all the query details.

> we still need a way for a receiver to provide a URL

Why? What's the use case for that? Couldn't SPSP just always be about translating an `account@host` identifier into the query result?

> Exactly. A payment is not the same thing as an invoice. Let's not confuse a "request to be paid a fixed amount for a specific thing" with an invoice.

Okay. The example I gave above doesn't mention an invoice. It happens to be a payment for a specific amount and if you want to know what it's for you can go to the given URL.

**Comment by adrianhopebailie** [comment]
>> we still need a way for a receiver to provide a URL
> Why? What's the use case for that? Couldn't SPSP just always be about translating an account@host identifier into the query result?

The use case is a receiver passing "some identifier" to the sender and the sender using this to get all the info they need to make a payment.

What you're proposing is that the identifier is always in the form `account@host` which makes it difficult to do things like provide a receiver reference.

In contrast, if the identifier is a URL by default it's a lot more flexible. It can have query string params for example.

Nothing prevents us from having an optimization for `account@host` that saves a roundtrip vs "discovery via WebFinger then query" but that is an optimization on the core protocol which is a query that starts with a URL.

Note that defining new `.well-known` namespaces shouldn't be taken lightly. They're intended for site-wide meta-data (not as a general lookup end-point for individual site resources). 

See: https://tools.ietf.org/html/rfc5785#section-1.1

**Comment by adrianhopebailie** [comment]
> Okay. The example I gave above doesn't mention an invoice. It happens to be a payment for a specific amount and if you want to know what it's for you can go to the given URL.

Let's drop `"type": "invoice"`

**Comment by justmoon** [comment]
Based on @emschwartz' example, with the following changes:

* Drop the `type` as per @adrianhopebailie's suggestion, as we don't want to hard-code use cases.
* Bring back the `ledger_info` as a separate object. It's more readable to separate the information that the receiver controls from the information that it's merely forwarding from the ledger.
* Let's continue to use webfinger for now - if we decide to change it later fine, but it's an optimization and not urgent.

``` json
{
  "shared_secret": "itsasecret",
  "destination_account": "someledger.merchant.111-7777777-1111111",
  "maximum_destination_amount": "10.40",
  "minimum_destination_amount": "10.40",
  "receiver_info": {
    "name": "Amazon S.A.",
    "type": "invoice",
    "info_url": "https://www.amazon.com/gp/your-account/order-details?ie=UTF8&orderID=111-7777777-1111111",
    "image_url": "https://amazon.com/images/logo.png"
  },
  "ledger_info": {
    "currency_code": "USD",
    "currency_symbol": "$",
    "scale": "4",
    "precision": "10"
  }
}
```

We need to move forward since a bunch of projects are blocked on getting SPSP with PSK merged. This almost certainly won't be the final version of the protocol, so I'm not too worried if certain changes aren't part of this revision.

**Comment by emschwartz** [comment]
Also note that we should still use the HTTP cache headers to specify how long the `shared_secret` is valid for
