### ISSUE TITLE
Mention timeout in the route cost function

### ISSUE THREAD

**Issue by michielbdejong** [interledger/rfcs#155]
When a connector announces a route to another connector, it supplies a cost function which is currently a piecewise-linear relationship between cost-in and cost-out, right?. This does not allow an announcing connector to say anything about the speed of a route.

That's fine as long as all ledgers, connectors, and network connections are roughly equally fast / slow. But it's suboptimal when speeds differ. On the one hand, a payment may timeout prematurely, which means the payment fails, so that's bad. On the other hand, it may timeout too late, which is a waste of time.

I would propose to add 1 integer to the route announcement, namely: recommended timeout for this route, in milliseconds. Connectors are free to ignore this number in their routing strategy, but when forwarding a route announcement, they are required to include it. They can for instance just fill in the same timeout + 1000 ms.

Knowing the recommended timeout for a payment would make sure payments don't timeout too soon, and don't timeout too late.

The real motivation for proposing this is not so much that I worry about suboptimal timeout values, but that I would like certain existing (distributed) ledgers to join interledger, and they may be so slow that all payments to them would timeout if they don't have a way of saying "Warning: Slow ledger, please be patient". Such slower ledger would in practice never occur as intermediate hops, but if the source account or destination account is on a slow ledger, then it's a choice between delivering slowly, or timing out prematurely and not delivering at all.

**Comment by sentientwaffle** [comment]
Isn't this covered by `min_message_window`?

**Comment by sharafian** [comment]
I think the problem with one recommended or maximum timeout is that it doesn't give connectors an opportunity to increase their rates for payments with longer timeouts. If you're holding funds for more than a few seconds, you might lose money due to changes in FX rates (or due to opportunity costs, if you're an extremely busy connector).

I think that instead, we should add a time dimension to the cost function. `ilp-core` already has this as an optional parameter, so the large change would be to the broadcasting/routing code, which is already being overhauled.

# Receiving on a slow ledger

## Example

Let's say that Alice wants to send 0.1 bitcoin to Bob. Alice would set her timeout to about an hour, in order to accommodate the speed of the receiving ledger (Bob could tell her what to set the timeout to during the SPSP phase).

Alice sends a quote to the connector, with `destination_amount=0.1`, `destination_account=g.crypto.bitcoin.bob`, and `destination_expiry_duration=3600`.

The connector on Alice's ledger gets the cheapest route to `g.crypto.bitcoin.` from their routing table. This route has a rate curve, which associates source amount, destination amount, and expiry duration.

The connector looks up the source amount corresponding to `destination_amount=0.1` and `destination_expiry_duration=3600`. If a timeout of 1 hour is supported, they can calculate a source amount from the curve, e.g. $120. If a timeout of 1 hour is unsupported, (the rate curve doesn't have an expiry that long in its domain) then the connector will return an error.

**Note that this isn't the same as looking for the fastest route, or filtering the routing table by supported timeout. The assumption is that all routes to a single destination support the same timeouts**. We can make this assumption because there is no reason for a connectors to peer with one another over slow ledgers, rather than using a payment channel and periodically settling. So if there's ever a long timeout, it's because the payment is being delivered on a slow ledger.

# Sending from a slow ledger

If you want to send _from_ a slow ledger, it's much easier.

If a connector sees an incoming payment that's going to take a long time, then they can wait until it's proposed, and then send the payment to the recipient and get the fulfillment quickly. Because the sender's timeout is so long, the connector has ample time to present this fulfillment to the slow ledger, without leaving their own liquidity tied up for a long time.

**Comment by emschwartz** [comment]
Can we close this now? I think we're going to get rid of the liquidity curves and highly variable timeouts
