### ISSUE TITLE
idea: timeout-less transactions

### ISSUE THREAD

**Issue by michielbdejong** [interledger/rfcs#159]
I wonder whether the Interledger could support transactions where no explicit timeout is specified. 
Instead, a sender or previous hop can send a 'please reject' message when they feel it's taking too long, or next hops could timeout spontaneously / out of courtesy.

This means the sender takes more risk, and the connectors take either different or less risk.

* two-hop (one-connector) case:
  * the sender now makes a payment to the connector that does not time out. This means the connector can run off with the money. To mitigate this, the sender will use a well-trusted connector and send only small (or even micro) payments at a time.
  * the connector no longer has to worry about the risk of the source ledger being down or unreachable at the moment of timeout, which IMHO removes a lot of attack surface. Instead, it has to worry that payments to unreachable recipients will never time out, meaning they will be exposed on the destination ledger, even if at the same time they are themselves holding the same or even a slightly higher amount on the source ledger.

* three-hop (two-connector) case:
  * the second connector, instead of worrying about whether the first connector will be reachable when its escrow times out on the trustline, now worries about whether the recipient will be reachable.

* dealing with unreachable recipients
  * when the recipient is unreachable, the sender, as well as all connectors involved, have money on hold
  * the sender can, however, cancel the whole payment by fulfilling the payment. The process for this would require some extra though, because ledgers should allow a 'fulfill-to-sender' operation, in which the connector gets its money back, and the recipient loses the right to fulfill this transfer (basically, I guess, MultiSig).

**Comment by michielbdejong** [comment]
![img_20170220_095118](https://cloud.githubusercontent.com/assets/408412/23118616/1518eeb8-f755-11e6-8c89-c00fb9616947.jpg)

**Comment by michielbdejong** [comment]
As discussed, there are two problems with this:
- the sender has no way to get their money back from the connector. For this, you could still set a timeout of, say, one week.
- it would require ledgers to differentiate between final recipient or next connector, because if you allow more than one hop, the first connector could steal money from the second connector. For this, you could still keep the initial window of 10 seconds before sender-cancel is allowed.

So then you would split what is now the timeout time into 'may timeout' and 'must timeout' times, for each hop:

````
phase  sender-cancel allowed? recipient-cancel allowed? recipient-fulfill allowed?
1                 no                      yes                      yes
2                yes                      yes                      yes
3                yes                      yes                       no

phase 1 could take, say, 10 seconds, that's what we have now, up to the 'may timeout' time.
phase 2 could take, say, a week, that's what protects connectors against timeout attacks.
phase 3 is everything after the 'must timeout' time.

**Comment by justmoon** [comment]
If I understand the proposal correctly, it is about the addition of a `retract` message. (The "give up" message already exists in the implementation and is called [`rejectIncomingTransfer`](https://github.com/interledger/rfcs/blob/607545526a40894a1e671479cded26b3413d0b3d/0004-ledger-plugin-interface/0004-ledger-plugin-interface.md#rejectincomingtransfer).)

The issue with a retract message is that it essentially nullifies the escrow. If the sender can retract at any time, then the receiver of a transfer gets no protection at all.

![screenshot from 2017-02-20 18-01-22](https://cloud.githubusercontent.com/assets/53233/23134899/d2533fd8-f796-11e6-8259-15487a766c4d.png)

And if we don't have a `retract` message and no timeout, then a malicious receiver can cause funds to be locked up forever:

![screenshot from 2017-02-20 18-06-31](https://cloud.githubusercontent.com/assets/53233/23135057/5ae0d22a-f797-11e6-828c-6a03ce23ae87.png)

You mention some additional trust assumptions beyond the basic Interledger trust assumptions. However, note that - in the general case - the connector has to assume that the "sender" is actually just another connector and the real sender is several hops away on an anonymous untraceable ledger. The same goes for the recipient. This is why we think connectors can mitigate risk from the ledgers - if a ledger turns out to be super-risky/evil, well the connector chose them, so it was their job to do their due dilligence. But connectors have no way to know or influence which senders or receivers they service, at least not if we want to keep the network open. So we can't make any assumptions about what the receiver will do, such as deliver the fulfillment or what the sender will do, such as not retract a transfer.

**Comment by michielbdejong** [comment]
Good point about the connector trusting the ledger and not the sender. I agree that for most ledgers, the current system makes the most sense. It's a good trade-off between simplicity and effectiveness.

For trustlines, I'm not sure whether hard timeouts make any sense though, because there's no third-party who can enforce them, right? On a trustline, there's nobody else around can tell the sender "you're retracting too early!" or tell the sender "you're fulfilling too late!". Then, it's just two parties who trust each other, and the concepts of "too early" and "too late" are flexible as long as both agree on it.

I still have a feeling that the timeout mechanism can be an agreement on top of the lower layer of just "fulfill"/"reject" and ledger balances. But I'll think about it some more :)

**Comment by emschwartz** [comment]
Can we close this now?
