### ISSUE TITLE
Question: Clarify ILP Packet Design

### ISSUE THREAD

**Issue by sappenin** [interledger/rfcs#189]
Some of the early designs for Interledger Packets used the notion of "headers" to attach data to a packet, as opposed to static attributes.  Examples include [this initial binary prototype](https://gist.github.com/justmoon/a59fd43958ce421c8b4a88d5143c718b) of the InterledgerPacket or this proposal for the structure of an [Interledger Error packet](https://github.com/interledger/rfcs/issues/150#issuecomment-288815583).  

These structures seemed to allow for three types of information to be included in a packet:

1. **Metadata** (e.g., a timestamp or a system-traceId or anything that doesn't collide with item-2 below)
1. **Required fields** (e.g., Amount and Address)
1. **Wrapped Packet 'data'** (e.g., data supplied by a higher-level protocol)

However, the latest [ILP Payment Packet Format](https://github.com/interledger/rfcs/blob/master/0003-interledger-protocol/0003-interledger-protocol.md#ilp-payment-packet-format) seems to have moved away from using headers and instead use pre-defined fields+data, which seems to have removed the ability to attach meta-data to an ILP packet.

1. Am I misunderstanding the current design of the Payment Packets?
1. If so, how would one attach meta-data to a packet without affecting a higher-level protocol's usage of the `data` field?

**Comment by adrianhopebailie** [comment]
@sappenin - My understanding of the current design is that the `data` element is used to store the meta-data.

The meta-data and how it is stored is defined by the transport protocol an example being PSK which puts something in the `data` field that looks like an HTTP request (including headers and data).

**Comment by sappenin** [comment]
Thanks @adrianhopebailie!  To clarify, are there not times when an ILP node might want to add some kind of meta-data without disrupting the `data` in the packet?

**Comment by adrianhopebailie** [comment]
The ILP Packet is an end-to-end transport. No intermediary node should be changing what's in there.

**Comment by emschwartz** [comment]
Good question. You've got the current design correct and you're right that it doesn't have as good a way to handle attaching metadata as some of the previous versions.

One place that metadata _can_ be included now is in the [Public Headers](https://github.com/interledger/rfcs/blob/master/0016-pre-shared-key/0016-pre-shared-key.md#public-headers) in the PSK or IPR data. That may not be ideal because payment intermediaries technically should not look at the packet data and must not require specific fields to be there. In a use case involving a closed network, participants could agree that all senders will include a system trace ID in the PSK public headers.

If this solution is insufficient there are two options for sending metadata in a different way:

1. Metadata field in the ILP packet - this was something we considered but a) theoretically you would put data here that's meant for intermediaries or meant to be modified by intermediaries but we didn't actually have a use case for this, b) we weren't sure what a reasonable encoding or size limit would be, c) if the metadata is hashed as part of the condition it can't be modified by intermediaries and if it isn't there's no guarantee that it'll be relayed by each connector
2. Separate `extraHeaders` in ledger layer transfer - this was the [conclusion of the discussion](https://github.com/interledger/rfcs/issues/127#issuecomment-277635232) but we didn't actually implement it. I think it would be fine to add this to the implementation, but we need to define the size and encoding. This also will have the problem that there's no guarantee the connectors will forward this, but that may be okay depending on what the use case is
