### ISSUE TITLE
RFC 0016: Should public headers be removed from PSK?

### ISSUE THREAD

**Issue by sharafian** [interledger/rfcs#197]
(From a discussion with @adrianhopebailie and @justmoon, about https://github.com/interledger/rfcs/issues/196)

Currently, PSK data is split into a set of public headers and private headers, as well as application data. The private headers and application data are encrypted (assuming encryption is enabled), and the public headers contain information on how the receiver can decrypt them. It's important to note that although the public headers can be read by any connector in a payment, it is inadvisable for them to do so. No connector should make assumptions about the data field of the ILP header.

If the public headers shouldn't be used by anyone other than the receiver, then the receiver should only need them for decrypting the private headers. All other information could then be put in the private headers and application data. So we can replace the list of arbitrary public headers with a much simpler wrapper, meant only to handle encryption.

This would mean that PSK would be composed of:

- A binary encryption wrapper, containing:
- A PSK status line
- A single list of PSK headers
- An empty line
- Arbitrary application data

Instead of the current structure, which is:

- A PSK status line
- A list of public PSK headers
- An empty line
- Encrypted data, containing:
- A list of private PSK headers
- An empty line
- Arbitrary application data

### Open questions:

- Is there any case where the ILP header needs to carry metadata that all connectors can read, or is the `transfer.custom` property sufficient?

- Should the encryption wrapper be its own protocol, or should it be a part of PSK? Should PSK stay in its unaltered current state, making encryption wrapper + one set of headers into its own transport protocol?

- Should the encryption wrapper have a `ciphertext=plaintext` option, or should information on whether a packet is encrypted be auto-detected or put into the ILP address?

- What exactly should the format of the encryption wrapper be?

- How should multiple encryption algorithms be handled?

- Should the nonce be a part of the encryption wrapper?

**Comment by adrianhopebailie** [comment]
Why do we need to define a new protocol here at all?

The ILP Packet is a an end-to-end transport for data sent from the payer to the payee of an Interledger payment.

Why not re-use existing application layer protocols that are transported using TCP or UDP packets?

For encryption and integrity we can simply re-use the TLS [application protocol](https://en.wikipedia.org/wiki/Transport_Layer_Security#Application_protocol) packets and inside those re-use HTTP.

We avoid a lot of the complexity of TLS because we don't need the handshake but we should re-use the data formats for simplicity.

**Comment by mDuo13** [comment]
I'm very hesitant to advocate for such drastic changes to PSK _after_ we have established a stable version for it. Although it's tempting to continue improving the spec to iron out inefficiencies and imperfections, I think the improvements have to meet a high standard to justify them.

As written, PSK is relatively simple to understand and implement. There are some inadvisable ways to use it, but those are clearly stated in the spec.

Changing the outer headers to a binary format seems simple and helpful at first, but the more I think about it, the more disruptive and confusing I think it is likely to be in the long run. I worry about ongoing maintenance/synchronization issues if we tie our spec explicitly to TLS, HTTP, or both. (I do agree that we should not reinvent the wheel for the sake of being different, so copying the TLS/HTTP formats verbatim where appropriate is sensible to me.)

Overall, I'm tentatively against.

**Comment by adrianhopebailie** [comment]
> I worry about ongoing maintenance/synchronization issues if we tie our spec explicitly to TLS, HTTP, or both.

@mDuo13  Can you explain what you mean by this? I'd consider leveraging an existing standard as an advantage (we have less to do ourselves) than a risk.

The way I'd document this is that we use TLS v1.3 but only support a very specific set of Cipher-suites.

**Comment by mDuo13** [comment]
Using a specific version of a specific spec makes sense. But if we tie ourselves to another spec, there's always the question of... do we update to match that spec? When TLS 1.4, or TLS 1.3.1, or TLS 1.3 with errata, are formally specified, does that have an impact on us? The changes to TLS are not likely to take into account our nonstandard usage, so it's entirely possible they'd make changes that break our use case or are more inconvenient for us. Then, instead of being able to leverage existing implementations, we'd be stuck between requiring people to use implementations of the older spec versions, or changing the protocol for reasons we'd rather not.

**Comment by adrianhopebailie** [comment]
> But if we tie ourselves to another spec, there's always the question of... do we update to match that spec? When TLS 1.4, or TLS 1.3.1, or TLS 1.3 with errata, are formally specified, does that have an impact on us? 

The TLS record includes the version in the header so I don't think that's an issue. 

> The changes to TLS are not likely to take into account our nonstandard usage, so it's entirely possible they'd make changes that break our use case or are more inconvenient for us.

I don't think this is likely. TLS is just a wrapper around application layer packets so as long as that's all we're doing it is exactly what we need.

**Comment by emschwartz** [comment]
PSKv1 is being replaced with PSKv2, which does not have public headers https://github.com/interledger/rfcs/pull/351
