### ISSUE TITLE
clarify meaning of `destination_ledger` in quote response

### ISSUE THREAD

**Issue by michielbdejong** [interledger/rfcs#207]
The way I interpret `destination_ledger` in quote response, is that the quote is valid for *any* destination account on that entire ledger, not just for the `destination_account` from the quote request. @adrianhopebailie says (IIUC?) this cannot be generalized in this way, and the quote is just for the destination account in question (might be entirely different for other destination accounts on the same destination ledger)

The [current text](https://github.com/interledger/rfcs/blob/master/0008-interledger-quoting-protocol/0008-interledger-quoting-protocol.md#response-message-format-success) isn't very clear about it.

Which one is it?

**Comment by adrianhopebailie** [comment]
I believe we need to distinguish between costing routes and getting quotes.

Costing routes helps payers/senders to determine how much to send without needing to a do a quote per transaction. 

Example:
If you have a curve for `g.za.bank` then you have a good idea of what it will cost to send to `g.za.bank.g34rg87tefyg2uo3trf`. 

But it's still possible that the payment will fail because there is something about that specific address that means delivering to it costs more than most addresses in that sub-net. 

This will usually be a business rule that it makes no sense to encode in the route information such as a transaction type.

When the payment fails the payer could then send a quote request for that specific address and the outcome should be a quote that that has an almost 100% of success.

**Comment by michielbdejong** [comment]
> it's still possible that the payment will fail because there is something about that specific address that means delivering to it costs more than most addresses in that sub-net.

That's new to me, I thought route broadcasts were supposed to already take into account all business rules. If the protocol is supposed to allow for structural discrepancies between the "theoretical" liquidity curves given in route broadcasts and the ones used "in practice" in quote responses, then we should document that explicitly.

cc @emschwartz

**Comment by adrianhopebailie** [comment]
> That's new to me, I thought route broadcasts were supposed to already take into account all business rules.

How can they?

Assume I have a curve for the route `g.za.bank` and the bank introduces a new rule that means when a customer receives payments of a certain amount there is a surcharge to handle some admin fee. The bank can encode this in a new route and instead of providing the address `g.za.bank.g34rg87tefyg2uo3trf` they provide the address `g.za.bank.bizrule1.g34rg87tefyg2uo3trf`.

Entities upstream have not heard of the new route `g.za.bank.bizrule1.` so they assume that address is under the route `g.za.bank.` and price accordingly.

The first payment will fail and then the upstream entity must decide how to handle this. It will likely attempt to get a curve for the new route and start to price accordingly but this situation will continue repeating itself every time new business rules are introduced.

What's worse is that if there are multiple rules that are applied in combinations. The number of routes grows exponentially. 

Also, what's the difference between the routes `g.za.bank.bizrule1.bizrule2` and `g.za.bank.bizrule2.bizrule1`. They should have the same curve but connectors will see them as distinct routes.

**Comment by michielbdejong** [comment]
But when using SPSP for instance, you can announce that your account is `g.za.bank.bizrules1and2.g34rg87tefyg2uo3trf` without problem, right?

You are right that if there are 4 bizrules which can occur in 16 combinations, then the bank will have to announce 16 different liquidity curves, but announcing 16 liquidity curves will still be easy compared to explaining all those curves to their customer support department. :) What is the maximum number of different bizrule-combinations you think one bank would, realistically, have in practice?

**Comment by adrianhopebailie** [comment]
> But when using SPSP for instance, you can announce that your account is g.za.bank.bizrules1and2.g34rg87tefyg2uo3trf

Right but how does an upstream entity know that the route they have for `g.za.bank.` is not specific enough?

Also, how do you deal with regularly changing rules or combinations of these. I agree that in theory this is all possible but I think we need to test against some real use cases.

**Comment by emschwartz** [comment]
The ASN.1 definitions are correct but the ILQP spec and the current implementation are out of date.

The quote source or quote destination amount messages only apply to the specific account you asked for a quote for. When you ask for a liquidity curve, the field [`appliesToPrefix`](https://github.com/interledger/rfcs/blob/master/asn1/InterledgerQuotingProtocol.asn#L36-L42) tells you how much of the address that liquidity curve applies to. If it only applies to the specific account, the full account will be in that field. If it applies to a more general prefix (e.g. all accounts on the same ledger or subledger), the most general prefix will be in there.

**Comment by michielbdejong** [comment]
ok, thanks! I'll create a PR to clarify it.
