### ISSUE TITLE
RFC8 and ASN1. GeneralizedTime usage

### ISSUE THREAD

**Issue by andrew-g-za** [interledger/rfcs#230]
Hi there,

I've been working on the java-ilp-core project to add support for the various ILQP packets.

The [ilqpliquidityresponse](https://github.com/interledger/rfcs/blob/master/0008-interledger-quoting-protocol/0008-interledger-quoting-protocol.md#ilqpliquidityresponse) defines the `expiresAt` field as an ASN.1 GeneralizedTime structure in [InterledgerTypes.asn](https://github.com/interledger/rfcs/blob/master/asn1/InterledgerTypes.asn)

The GeneralizedTime structure contains many optional portions (hours, seconds, fractions of seconds, and timezone), which could be problematic when used, particularly given the distributed nature of ILP. For example, the value of the `expiresAt` field in the ilqpliquidityresponse is meaningless if no timezone information is included but the quote crosses a timezone.

It also presents problems for parsing, see [interledgerjs issue 7](https://github.com/interledgerjs/ilp-packet/issues/7)

Is there not a case to change this to something more rigid and defined, and that mandates timezone information? Perhaps something like [date-time in RFC3339](https://tools.ietf.org/html/rfc3339#section-5.6)
or even a fixed string format YYYYMMDDHHmmSS.fff(+|-)hhmm where there is no chance for ambiguity?

**Comment by sappenin** [comment]
+1 to this request and using RFC-3339 since it appears to be a subset of ISO-8601 limited to Timestamps. That said, it might worth exploring the subtle differences between the two as regards language support. I know there is pretty good support in Java for ISO-8601, but haven't explored how things like Tomezome formatting would work if he spec required rfc-3339, but the libraries are actually using an ISO-8601 library to render an rfc-3339 timestamp. I'm not at a computer but perhaps something like Joda-time would support both, or maybe even the Jdk itself. Unsure about other languages.

See here for more details: https://stackoverflow.com/questions/522251/whats-the-difference-between-iso-8601-and-rfc-3339-date-formats

Maybe it would be safer to say this field is an ISO-8601 date/time stamp and then specify the required fields?

**Comment by adrianhopebailie** [comment]
@justmoon Do we need these packets to be canonical for the sake of signing?

There may be a case where a quote needs to be signed by the entity providing it in which case it may be important to define a format for the `expiresAt` field that can be deterministically encoded.

My suggestion would be to make this a fixed format that is compliant with RFC 3339 but is always expressed as UTC and always uses an upper-case `T` and `Z`:

`YYYYMMDDTHHmmSS.fffZ`

**Comment by andrew-g-za** [comment]
closing this issue, see #250
