### ISSUE TITLE
RFC-20 - Arranged password in Example Payment

### ISSUE THREAD

**Issue by elmurci** [interledger/rfcs#274]
When explaining how ILP works (_How ILP Works: An Example Payment_) in step 3 reads _"The receiver hears all about the payment and puts the password **they previously arranged** with the sender into the box."_ but it is not clear in the example how the sender and receiver agreed on the password as it is not mentioned in previous steps.

**Comment by professorhantzen** [comment]
Thanks for the feedback, always good to have more eyes on things.

The password exchange is described in the prior section "The Special Box", which also goes into the nature and function of the boxes. (The document is intended to be read from beginning to end and gradually build a complete picture.)

**Comment by elmurci** [comment]
Yeah I know, ok... the section earlier in the document is a more generic explanation on the Special Box concept.
As this section tries to explain an end to end example where all the concepts come together, 
I think it would be good to have a quick mention or a reference at least to help the reader.
But that's just my opinion.

**Comment by professorhantzen** [comment]
That's valid. My thoughts when writing it were that the Example Payment section focuses on what happens when a payment actually takes place, not so much on the setup of that payment / quoting etc which are quite involved. Maybe the intention for that section is not clearly communicated, as it did come across to you as an end-to-end example.

I also described most things only once if possible, to keep the document brief, but this does come at the expense of greater modularity between sections.
