### ISSUE TITLE
Mark the PrepareTransferRequest.executionCondition as Optional?

### ISSUE THREAD

**Issue by sappenin** [interledger/rfcs#287]
In the latest [CLP definition](https://github.com/interledger/rfcs/blob/8b65d63e3aeaadeeb40ca5d2c86722eadf11ab77/asn1/CommonLedgerProtocol.asn), the `executionCondition` field in `Prepare` is non-optional.

If we want to be able to support unconditional payments, shouldn't this field be marked as `OPTIONAL` per ASN.1 OER?

**Comment by emschwartz** [comment]
I don't think we should mix unconditional and conditional payments. We decided a while back to take unconditional payments out of the JS Ledger Plugin Interface and I think that was a good idea. If there's a case to be made for bringing back unconditional payments, at least as part of CLP (if not as something that's supported on the Interledger layer), I would argue that there should be a separate transfer type that doesn't have a condition or expiry rather than mixing the two into one type.

**Comment by michielbdejong** [comment]
I agree, and there actually is a use case for adding:
```js
{
  type: TYPE_BILL,
  requestId,
  data: {
    amount,
    protocolData: [
      {
        protocolName: 'vouch',
        contentType: 1,
        data: {
          call: 'roll back',
          wallet: 'test.eth.rinkeby.q3gwrtea4wfsrtegfgtrdsfsare',
          condition: <...>
      }
    ]
  }
}
```

https://github.com/interledger/interledger/wiki/Interledger-over-CLP#vouch:
> Note that this violates the design of CLP because this message would use the 'unconditional paid request' with a negative amount, if that request type would exist in CLP, but the current trustline balance can still be determined at any time by adding up all fulfilled CLP transfers in both directions, and all vouch protocol rollbacks in both directions.

I called it 'BILL' instead of 'TRANSFER' because to do the roll-back as a transfer, the amount would be negative, which would be weird because we use UInts everywhere.

**Comment by sappenin** [comment]
Great clarifications! I'm convinced and also in agreement, so I'll close this issue. Plz re-open if anyone has further thoughts.

**Comment by dappelt** [comment]
@michielbdejong  why do you create a new CLP packet type for your bill use case instead of using `Message`?

**Comment by michielbdejong** [comment]
@dappelt because `Message` doesn't have an `amount` field.

**Comment by dappelt** [comment]
@michielbdejong This boils down to how we envision CLP to be extended. So far, we planned to implement non-core CLP functionality via side-protocols. However, the `TYPE_BILL` packet that you are proposing would extend CLP not via a side protocol, but by adding a new CLP packet type.

Following the side-protocol design, you could put the amount in `protocolData`. For example:

```
{
  type: TYPE_MESSAGE,
  requestId,
  data: {
    protocolData: [
      {
        protocolName: 'vouch',
        contentType: 1,
        data: {
          call: 'roll back',
          wallet: 'test.eth.rinkeby.q3gwrtea4wfsrtegfgtrdsfsare',
          amount, // <-- AMOUNT
          condition: <...>
      }
    ]
  }
}
```
