### ISSUE TITLE
RFC-8: Send quote requests via Optimistic payments

### ISSUE THREAD

**Issue by emschwartz** [interledger/rfcs#29]
A neat trick... Connectors broadcast rate curves and routes to one another but more well-known connectors don't have much of an incentive to store much information about the less well-known connectors and ledgers.

If ILQP is implemented such that quote requests are sent over the Interledger as Optimistic payments, more central connectors might actually have an incentive to store the routing info of smaller ledgers and connectors. The way it would work is each successive connector would take a little bit of the Optimistic payment's value until the packet reached a connector that could actually answer the quote request. Therefore, if a more central connector can answer the request without having to query further down the chain it would (legitimately) keep more of that payment's value.

Note that connectors could pretend to know the route info and keep the full value of the payment. However, when the sender went to actually send the payment it would likely fail so this would just show up to earlier connectors and the sender as an unreliable route and they would avoid it in the future.

It's also interesting to note that quote requests will often be followed by payments worth even more, so there may be an even more direct incentive to respond to the quote request honestly.

**Comment by emschwartz** [comment]
cc @adrianhopebailie @justmoon

**Comment by adrianhopebailie** [comment]
Combining this with a connector-to-connector broadcast protocol is very powerful.

It's a tool that a connector can use to get certainty about a quote it produces and not a mandatory step in the quoting process.

It has a nice economic model. Because connectors are incentivized to hold good data, it makes sense they may pay to get it if they decide it's worth it.

Question: Would a mechanism for the ledger to also take a cut of the quote payment be useful?

**Comment by adrianhopebailie** [comment]
To expand on this a bit, we should define quoting as a simple relationship between a sender and the next connector. The sender (or a connector) get's a quote from the next connector and doesn't need to know how that connector got the quote. It may be generated from a rate curve or it may send out a quote itself.

It's even possible that a sender asks a connector for a quote and that connector pays (using an optimistic payment) for a quote from the next connector. It may be taking the risk of getting the quote because it believes it will make a good margin on the actual payment or it may have a separate business relationship with the sender that covers these costs.

So, whenever a node (sender or connector) wants to get a quote they can ask a neighboring connector by either requesting a quote to send a specific amount to a specific ledger or a rate curve to send to that ledger.

Note that the node requesting the quote could already have additional data about the rate curve or cost to send from the ledger they are asking about and the receiver (i.e. they may not be the same ledger). Combining this with the quote they get to form a final quote amount is not something we need to define in the protocol, it's logic that would be implemented in the connector/sender.

**Comment by justmoon** [comment]
> Note that connectors could pretend to know the route info and keep the full value of the payment. However, when the sender went to actually send the payment it would likely fail so this would just show up to earlier connectors and the sender as an unreliable route and they would avoid it in the future.
>
> It's also interesting to note that quote requests will often be followed by payments worth even more, so there may be an even more direct incentive to respond to the quote request honestly.

Not sure I get this. You're saying that the connector has no incentive to steal the money because the upcoming payment is worth even more to them.

If that's true and the upcoming payment is valuable to the connector wouldn't they be more than happy to respond to the quote request for free? So what is the purpose of paying this incentive in the first place if, for it to work, there must be a greater incentive already in place?

One of the reasons IL-RFC 4 combines message passing and payments into one, is because it may be useful in general to send money along with low-level ILP requests (e.g. route advertisements, route requests, quote requests, etc.) But in the case of quoting, I think it would only be used as a spam disincentive, not as a quote incentive, because the promise of profiting off of the payment is plenty of incentive for the connector to respond to quote requests.

----

For others reading along I want to provide some context:

Our current proposal for ILP routing deals with routes in three sections:

![screenshot from 2016-07-11 11-54-14](https://cloud.githubusercontent.com/assets/53233/16728444/3af88fbe-475e-11e6-8e32-e71d13b39b62.png)

1. Up from the peripheral sender into the well-known set
2. Through the well-known set
3. Down from the well-known set to the peripheral receiver

The receiver provides pre-generated rate information for the third leg of the journey. And the second leg is a simple lookup within the routing table of one of the well-known connectors. So the only leg where we actually cascade from connector to connector is on the first leg. I.e. we ask our local connector who asks their gateway, who asks their gateway and so on until we hit a connector who has rates for the well-known set. That should then be enough together with the rate hints from the receiver to give an estimate for the whole path.

Obviously this model may change as we develop new and better routing algorithms, but under the current model if we want to consider the incentives for cascading connector quotes, we are talking about the first leg only.

**Comment by emschwartz** [comment]
Closing because we're now doing end-to-end quoting
