### ISSUE TITLE
[BTP]: Indicate protocol version at connection establishment

### ISSUE THREAD

**Issue by dappelt** [interledger/rfcs#294]
To distinguish the current CLP protocol version from future CLP versions, we should include a CLP version number at connection establishment. We could use the [subprotocol mechanism](https://tools.ietf.org/html/rfc6455#section-1.9) of the websocket protocol for the client and server to agree on the CLP protocol version.

When establishing the websocket connection, the client indicates which CLP version he supports. He does this by setting the HTTP header `Sec-WebSocket-Protocol` to a comma-separated list of CLP versions he supports, e.g.: `Sec-WebSocket-Protocol: CLP-1.1, CLP-1.0`. The server selects a version from the list and sets the same HTTP header in the response to the selected version, e.g.: `Sec-WebSocket-Protocol: CLP-1.1`.

**Comment by dappelt** [comment]
There is a nice explanation on how to use WebSocket sub-protocols on MDN: https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API/Writing_WebSocket_servers#Subprotocols

**Comment by dappelt** [comment]
Evan asked me to have a look if WebSocket libraries for popular languages support the subprotocol mechanism. This is what I found:
- JavaScript: [ws](https://github.com/websockets/ws/blob/b32016995e9620ed6d5826464b2c3ee931e2240a/lib/WebSocket.js#L452) supports it.
- Java: [Java-WebSocket](https://github.com/TooTallNate/Java-WebSocket) allows to set [custom headers](https://github.com/TooTallNate/Java-WebSocket/blob/37e9b08425ffeb288766d4bd313f4a95e8e89de2/src/main/java/org/java_websocket/client/WebSocketClient.java#L120), so it should be supported.
- Rust: cyderize supports [it](http://cyderize.github.io/rust-websocket/doc/websocket/client/builder/struct.ClientBuilder.html#method.add_protocol).
- Python: websocket-client supports [it](https://github.com/websocket-client/websocket-client/blob/47b6030687056e89c3d7bff9965eb993a95f370d/README.rst#sub-protocols).

Feel free to leave feedback if your favorite supports WebSocket subprotocols or not.

**Comment by emschwartz** [comment]
To me the main question is whether this kind of protocol negotiation should happen in this protocol or before the connection is established.

These are the main things that need to be versioned and negotiated:
- BTP version
- Required subprotocols (for example, if you're using BTP for a payment channel with claims)
- Optional subprotocols (to, from, balance, info, etc)

Will peers know which of these they're going to be using before they connect?
- In the case of payment channels, they probably would. Or, the Bitcoin community might decide on a set of subprotocols and a BTP version and call that the Bitcoin Payment Channel Protocol 1.x. In that case you would either know up front what set of protocols you're going to be speaking (if there's only one), or you would talk about them as a group.
- In the case of symmetric trustlines, you probably would as well. That would be part of your peering arrangement and/or peering protocol.
- In the case of asymmetric trustlines I'm not sure. Would you have one Websocket URI you would connect to with different clients, each of which might support different features?

**Comment by michielbdejong** [comment]
I think we should distinguish between two problems, the language problem, and the list-of-services problem, they are two different things. If I go to a shop and try to buy "een appel", the answer might be "ja" or "nee", depending on whether that shop sells apples or not. Or it might be "I don't understand" if the shopkeeper doesn't speak Dutch. Those are two different problems. Stating that a peer speaks 'BTP-2' is orthogonal to stating that that peer offers, for instance, a quoting service.

From the context of who you're connecting to, you probably know that a frog for red.ilpdemo.org only support ILQP if you specify the `to: 'us.usd.red.connie'` side-protocol. That's the 'list-of-services' problem.

I used to think, we might as well use `/api/v1` and `/api/v2` so the client can choose, but @dappelt made me realize that that's not ideal. Suppose there is a network  where software updates each 6 months. One node in the network updates its software right away, from supporting version 3 and 4, to supporting versions 4 and 5. The rest of the network still supports versions 3 and 4, and only version 4 is still used. Now, a second node updates, and next time those two nodes connect, they will *automatically* start using version 5. It's worth automating this, because otherwise you either need a deterministic URL scheme, and connection will take longer (trying `/api/v5` first, and falling back to `/api/v4` if that first attempt times out), or the sysadmin of a node with `n` peers needs to update their server config `n+1` times instead of just once per six months.

**Comment by dappelt** [comment]
It cannot hurt if BTP implementations are explicit about the BTP version they speak. 

> These are the main things that need to be versioned and negotiated:
> - BTP version
> - Required subprotocols (for example, if you're using BTP for a payment channel with claims)
> - Optional subprotocols (to, from, balance, info, etc)

This proposal addresses the first bullet point. It is not suitable for a _choose-M-out-of-N_ scenario like we have it with BTP sub-protocols.

> In the case of asymmetric trustlines I'm not sure. Would you have one Websocket URI you would connect to with different clients, each of which might support different features?

Yes, absolutely. For example, an ILP Service Provider has users _Alice_ and _Bob_. Alice connects with her BitTorrent client that uses version BTP/1.0 and Bob connects with ILP-Jeopardy that uses BTP/2.0. You could compare this ILP Service Provider with a web server serving HTTP/1.1 and HTTP/2.0 requests. Having a web server that serves only HTTP/2.0 would lock out many clients.

**Comment by dappelt** [comment]
As just discussed, we decided that we don't need a version number for BTP. We expect the sub-protocol mechanism of BTP flexible enough to implement new features.

**Comment by michielbdejong** [comment]
This issue has become relevant again, since https://github.com/interledger/rfcs/pull/413 currently relies on BTP/2.0 and it would be nice to be able to just use a `wss+btp://` URL instead of a `wss+btp2://` URL.

OTOH, @adrianhopebailie would prefer to also allow loopback servers to speak languages that are not even BTP, so then we might need a versioning scheme outside the `wss+btp://` URLs anyway, and then we had better use that one mechanism for both the choice to use BTP and the choice to specifically use BTP/2.0

**Comment by adrianhopebailie** [comment]
I would also like us to use the `Sec-WebSocket-Protocol` standard as this makes implementing BTP on top of other WS stacks easier.

Many WS stacks (e.g. Jetty) allow for custom handlers that are invoked by the core stack based on the value of this header. Implementing BTP is a lot easier (and less tightly coupled to the specific stack) if we use sub-protocols.

So a big +1 from me for @dappelt 's original request
