### ISSUE TITLE
CLP/BTP Authentication

### ISSUE THREAD

**Issue by dappelt** [interledger/rfcs#299]
We need to settle on how connection authentication works in BTP. It can be done either inside of the connection (for a proposal see [here](https://github.com/interledger/rfcs/blob/da-clp-auth/00XX-common-ledger-protocol/00XX-common-ledger-protocol.md#authentication)) or before connection establishment. In any case, the spec should say something about authentication.

**Comment by dappelt** [comment]
A variant of doing authentication before connection establishment could go as follows:

1. The client makes a POST request to the endpoint `/login`. He sets the `Authorization` header to his credentials/auth token.
2. If the auth details are valid, the server replies with a specially crafted URL of the format `wss://ilpkit.example/websocket/long-random-string`. The last part of the URL is randomly generated and should not be guessable. The server remembers to which user he gave out a particular URL.
3. The client has 30 seconds to open a WebSocket connection to the provided URL. If the client does not try to establish a connection within 30 seconds, the URL expires.

Note that this procedure avoids putting long-lived secrets into an URL, as the current BTP implementation does.

**Comment by michielbdejong** [comment]
Why not just set an `Authorization` header on the http request that opens the WebSocket, then?

**Comment by dappelt** [comment]
That would be the best solution. Unfortunately, that is not possible with the [WebSocket API](https://developer.mozilla.org/en-US/docs/Web/API/WebSocket).

**Comment by adrianhopebailie** [comment]
Why not use a sub-protocol?

Simply include a protocol called `token-auth` and the content is a token that is used to auth the request.

That allows peers to define alternative ways of doing auth (like certificates) without impacting the core protocol.

**Comment by michielbdejong** [comment]
auth as a sub-protocol is basically the current proposal for https://github.com/interledger/interledger/wiki/Interledger-over-CLP#changes-to-setup

@dappelt what are your considerations for proposing this alternative now?

**Comment by dappelt** [comment]
> Why not use a sub-protocol?

That is one possibility. Here is my proposal for such a [sub-protocol](https://github.com/interledger/rfcs/blob/da-clp-auth/00XX-common-ledger-protocol/00XX-common-ledger-protocol.md#authentication).

> That allows peers to define alternative ways of doing auth (like certificates) without impacting the core protocol.

Doing the authentication outside of the BLT connection does not mandate a particular auth scheme. The auth scheme I detailed above is a recommended implementation, but if an implementor wants to use certs he is free to do so.

In fact, doing the authentication outside of the BLT connection provides more flexibility for customization than doing it inside the connection.

**Comment by dappelt** [comment]
> what are your considerations for proposing this alternative now?

@michielbdejong, my main concern is to avoid long-lived credentials in the WebSocket URL. I pointed out two alternative solutions to achieve this: doing authentication 1) inside the BLT connection and 2) before the connection is established. Both have pros/cons and are up for discussion.

Other than that, @evan raised the concern that if we do the authentication inside of the connection, the component that handles the authentication (e.g. ILP kit) would need to process CLP packets before handing off the connection into the plugin. (@evan please expand if there is anything else.)

**Comment by adrianhopebailie** [comment]
@dappelt I hadn't seen that proposal, it's along the same lines as what I think is a good way to do this.

I don't share @emschwartz concern. I would assume that the subprotocol processors would need to be pipelined?

So the auth component would sit at the beginning of the pipeline and look for the auth subprotocol data before any other processing. 

I'd suggest that the auth token is sent in every request as opposed to trying to establish some kind of session over the connection

**Comment by emschwartz** [comment]
I don't think the handlers would be pipelined. I would just imagine adding a handler per sub-protocol and then the thing getting incoming messages would pass the messages to the appropriate handler.

> I'd suggest that the auth token is sent in every request as opposed to trying to establish some kind of session over the connection

👎 . Why? Since Websockets are connection-oriented (and use TLS) anyway, why wouldn't you use a session?

I _think_ it would be better to assume the connection is authenticated and suggest using short-lived tokens in the URL. For connectors that are peering with one another, they can use the peering protocol to determine the URI and token to use. For clients, we could do something like add a Webfinger-based protocol (to go along with SPSP) that gives you an endpoint that you would authenticate with to get your WSS URI from. The main thing that makes me hesitant about that is needing to build webfinger support into the plugin implementations...

**Comment by adrianhopebailie** [comment]
> Why? Since Websockets are connection-oriented (and use TLS) anyway, why wouldn't you use a session?

Loose coupling. Auth is an application concern. You have logic at the transport layer that needs to look into the account system to auth the connection then you also have logic at the application layer that looks into the same account system to auth transfers. (I am referring to the traditional IP stack layers here)

You don't have to send the token with each message but it makes the implementation much simpler. You could have an auth component at the head of the pipeline that also does session management and looks for the `auth` and when it sees it it creates a session and passes through further messages until the session is destroyed. Question is do you then add a session id to the auth protocol?

Using the secure socket is certainly do-able it just makes the dependancy on Websockets even stronger. Not a bad thing if that's intentional but then I question why we bother having a binary message definition at all.

**Comment by michielbdejong** [comment]
Just discussed this on Slack with @emschwartz as well, we concluded it's very nice if auth is in the URL, then client/server implementations don't have to worry about anything except the URL. The exact template for where in the URL you put the token, is then out of scope for BTP implementations, and also they don't have to look at the http headers, or the client-side TLS cert, and they don't need to send any messages after connection.

**Comment by dappelt** [comment]
Declaring authentication out of scope for the BTP spec is fine with me. What's **NOT** fine is to use long-lived secrets in URLs.

**Comment by emschwartz** [comment]
@dappelt is that only when it's used in the browser?

**Comment by dappelt** [comment]
No, in general. If we plan to drop browser support though, we could easily pass the token in the `Authorization` Header. `ws` allows to set [headers](https://github.com/websockets/ws/blob/master/doc/ws.md#new-websocketaddress-protocols-options) in the HTTP handshake.

**Comment by dappelt** [comment]
Ok, let me know when you are done and the PR is open.

**Comment by michielbdejong** [comment]
@dappelt can we close this, since the PRs are open now? (#300 for spec, https://github.com/interledgerjs/ilp-plugin-payment-channel-framework/pull/21 for implementation)
