### ISSUE TITLE
RFC-4: Remove getConnectors method

### ISSUE THREAD

**Issue by emschwartz** [interledger/rfcs#32]
We've more or less agreed that clients and connectors should figure out what connectors to connect to on a higher level. We should remove the `getConnectors` method from the Ledger Plugin Interface.

**Comment by emschwartz** [comment]
cc @justmoon @diminator @ameensol

**Comment by sentientwaffle** [comment]
@emschwartz what will `js-ilp-core`'s `client.quote` API look like, then? Should it accept a list of connectors to query?

**Comment by diminator** [comment]
I am assuming that the quoting/discovery be out-of-ledger responsibilities?

**Comment by emschwartz** [comment]
I think that information would be stored in the (core client's) routing table. I don't have a totally clear picture of how this would work. @justmoon could you explain what you're thinking about this?

**Comment by justmoon** [comment]
@emschwartz is correct, you'd configure it via the routing table. I.e. 99% of the time client would put a single catch-all connector ("gateway"?).

**Comment by adrianhopebailie** [comment]
@emschwartz my understanding of this was that it returned an opaque ledger-specific identifier for the connectors so that the client could pass transfers to the ledger and direct them at a specific connector.

How would the client know the local-to-the-ledger identifier for the connector?

i.e. The client (and connectors) communicate with each other to get quote and route data and populate their routing tables but when they need to make a transfer to a neighboring connector they do so by addressing that transfer to the connector using it's local address. Can we assume that connectors will store local/ledger specific addresses for their neighboring connectors in their routing tables?

**Comment by justmoon** [comment]
> How would the client know the local-to-the-ledger identifier for the connector?

The routing table has a column "Next Hop" which is the ILP address of the connector, e.g.

I want to send/forward to `us.wf.bob`, the only ledger I'm connected to is `cn.alipay`. So I look for the longest matching prefix known to me, which is `us.` in my routing table. The Next Hop for that entry is `cn.alipay.yuhao`. So I send to `cn.alipay.yuhao`.

**Comment by adrianhopebailie** [comment]
> The routing table has a column "Next Hop" which is the ILP address of the connector

How is this populated?
