### ISSUE TITLE
Do unconditional payment channels in connectors cause chunked payments for users?

### ISSUE THREAD

**Issue by michielbdejong** [interledger/rfcs#353]
From a user's point of view, transaction fees being equal, chunked payments are strictly worse than atomically-settled payments, because they provide less guarantees. You need to resort to chunked payments if the network is not able to atomically settle your entire payment all at once.

If connectors use a trustline, and can't route your payment over that, then it's likely that the trust limit of that trustline has been reached, and they also can't route it if you divide it into chunks.

If connectors use on-ledger escrow, and can't route your payment over that, then it's likely that the account balance has been exhausted, and they also can't route it if you divide it into chunks.

If connectors use conditional payment channels, and can't route your payment over that, then it's likely that the channel balance has been exhausted, and they also can't route it if you divide it into chunks.

If connectors use unconditional payment channels, and can't route your payment over that, then it's likely that the channel balance has not been exhausted yet, but that only the max in-flight (usually much lower than the channel balance) has been exhausted, and so they will likely be able to route it if you divide it into chunks.

However, as a sender, dividing your payment into chunks means your payment can no longer be settled atomically (instead, each individual chunk is settled atomically, but that's not even so useful if you use small chunks).

**Comment by michielbdejong** [comment]
Could this be an argument for using conditional payment channels instead of unconditional ones?

**Comment by emschwartz** [comment]
I think the two biggest reasons connectors would use low Maximum Payment Sizes are:
1. Minimize Free Option - the longer the payment's timeout is, the more you have to account for exchange rate volatility in your fees and deal with people accepting payments only if the rate moves in their favor. If the time outs are very short, this is less of an issue.
2. Minimize Fulfillment Risk - if connectors make the payment timeouts shorter by keeping their Min Message Window low, they increase the risk that they might be unable to pass on the fulfillment in time and thus lose money. Small payment amounts minimize the impact of this risk.

Conditional payment channels are no different than on-ledger escrow from the perspective of 1. because you need to build the ledger's worst case processing speed into the payment time out.

If we wanted to build protocols that could handle the full range of possibilities for payment times and ledger types, we would need to use liquidity curves with an extra time dimension added and build in rollback fees to make the free option not free. Roll back fees can always be stolen by intermediary connectors, so senders would need greater trust in the whole payment path. Every connector would also need to maintain multiple routing tables for each timeout and payment size so they know which paths can support a given combination.

The other reason to build for more homogenous payments is interoperability. We could set up the system described in the previous paragraph but then may find that in practice there isn't enough overlap in the sorted options to actually make payments, or we may find that only some least common denominator actually works. If the least common denominator is small, fast payments we might as well just build for this anyway. (This is the same reason we made conditions only Sha256 instead of Crypto Conditions in https://github.com/interledger/rfcs/issues/153)

Final note: connectors can set their Maximum Payment Size however high they like. If connectors get better at handling the two risks outlined above, the average path MPS may increase to the point where most payments don't end up getting chunked.

**Comment by michielbdejong** [comment]
Thanks for the explanation! In any case, this issue has become irrelevant since our recent decision to make all on-ledger transfers unconditional.
