### ISSUE TITLE
Document Web Monetization and compare to IL-RFC-14

### ISSUE THREAD

**Issue by michielbdejong** [interledger/rfcs#405]
In https://github.com/sharafian/web-monetization-leaderboard and www.siren.sh, @sharafian is using a protocol that, IIUC, does not use 402 responses with `Pay` headers, and actually allows two flows, one in which payment is required, and one in which payment is optional. We should document the comparison, and decide if we want to document that newer approach (and if we want to support it on the testnet), and also if we want to continue using http-ilp and this newer approach side-by-side.

For now, on the testnet, we only have https://letter-shop.herokuapp.com/ which supports http-ilp as documented in IL-RFC-14, but we can add more experiments if desired!

@sharafian I understand your proposal is to use http-ilp for machine-readable http requests (paid API calls) and to use your newer approach for human-readable ones (humans viewing html using a browser), right?

**Comment by sharafian** [comment]
Yeah, http-ilp is desirable for APIs because it charges a fixed price and pays once. The new protocol, which we're calling "Web Monetization" right now, is better for content because the amount paid is entirely up to the user. The longer the user stays on the page, the longer their extension will be sending money to the site, but their extension also has the option to not pay at all. Just like most sites don't care about an ad-blocker-blocker because they would rather leave an impression on the user than not show them anything at all, most sites probably won't turn away users if their traffic is not monetized.

**Comment by michielbdejong** [comment]
Can you document your Web Monetization proposal somewhere?

**Comment by michielbdejong** [comment]
Thanks for starting that! Discussion continued there.
