### ISSUE TITLE
RFC-26: Should payment pointers support ILP addresses?

### ISSUE THREAD

**Issue by justmoon** [interledger/rfcs#409]
While reviewing the Web Monetization spec, I noticed that HTTP URLs and email addresses have a really neat property that payment pointers lack: They allow you to skip discovery (DNS).

For instance: I can tell you to go to http://google.com, OR, I can tell you to go to http://216.58.195.78 - Now, why is that useful?

Discovery can be a fairly expensive step, especially with the current payment pointer proposal that requires you to do DNS + TCP + TLS + HTTP to look up a pointer. In some cases, it may be convenient to put in an ILP address and shared secret where a payment pointer is expected.

But what should it look like? ILP addresses look the same as domains, so it's impossible to tell which you are dealing with. Maybe the `~` (tilde) character could symbolize an ILP address because it is allowed in ILP addresses, but not in domains.

E.g. `$~g.zero.neutron.bob`

Still leaves the question of how to express the shared secret. Maybe with a colon like an IP port?

E.g. `$~g.zero.neutron.bob:bYmO7sZfSErf2joYaAe10flrDDGGxBqILyIUIYAvA1Y`

**Comment by sharafian** [comment]
One thing about payment pointers is that they're not technically PSK specific. The current SPSP implementation passes `Accept: application/spsp+json` but other protocols could use payment pointers to set up other protocols. Adding ILP Address+Shared Secret to payment pointers directly puts PSK/SPSP as a special case. It would also limit the number of required fields that we could add to SPSP. It might be fine to say that payment pointers are just for SPSP, but that's not the case just yet.

Another (much smaller) issue is that due to the similarity between ILP addresses and domain names, you could try to spoof a payment pointer by using a similar looking domain or ILP address. Of course, that's less of an issue if there's a shared secret in there but still something to think about.

**Comment by emschwartz** [comment]
I like this direction of being able to skip the HTTP lookup and making payment pointers useful in contexts like Web Monetization and HTTP headers.

It seems like the main issue is that we don't have a great story yet on protocol identification or version negotiation. `http:` tells you that you should speak HTTP to that endpoint, which assumes a certain transport protocol. We could say that `$` means SPSP, but I don't think our application and transport layers are nearly finished enough to pin to a specific version of either of them.

I think we need the payment pointer format to include the protocol and we could do that in a couple of different ways:
- Make it a proper URI format and put the protocol first
- Stick the protocol after the ILP address but before the data that is meant for the protocol (that could be a shared secret to go directly to PSK, or a public key for something like PSK-ECDH)
- Recommend that every protocol include a protocol identifier at the beginning of it's shared secret or other data (@justmoon brought up a good point that I wrote up in https://github.com/emschwartz/ilp-protocol-paystream/issues/14 that we should make it impossible for a client to successfully connect to a receiver speaking a different protocol)

**Comment by adrianhopebailie** [comment]
While I recognize some of the issues here are valid, I think we're missing the point of payment pointers. They are not the "DNS" of ILP they are the email addresses.

These are intended to be easy to convey, simple identifiers that are re-usable and designed so they are easy to serve as either an individual or a third-party host.

It sounds like what you want is just a new URI scheme, maybe `ilp:`?
