### ISSUE TITLE
Proposal: Our transport layers deal with condition generation, memo encryption, ...

### ISSUE THREAD

**Issue by justmoon** [interledger/rfcs#43]
Issue #28 proposes the removal of Optimistic, Universal, Atomic as transport protocols.

@emschwartz suggested we could bring back conditions as a condition layer, because they are end-to-end and need to be standardized.

In addition to that, this layer could also deal with encrypting the memo to the recipient (we already have the recipient's public key in some of the layer types mentioned above.) 
## User-defined Transport

There is no condition and no expiry. The memo is unencrypted.

``` js
sender.getCondition(condition) 
```
## Interactive Transport

Receiver generates the condition and provides a payment request (with a standard format) to the sender. 

``` js
receiver.generateCondition(ilpPacket)
sender.getCondition(multiPaymentRequest | previousFulfillment)
```

As an additional feature, we could have a condition whose fulfillment is another payment request (including a condition), such that multiple (pre-planned) payments can be expressed by one original payment request. This is useful for repeated payments or other predictable payments between the same participants.
## Passive Transport

Receiver has an Ed25519 public key. The sender generates the condition from this key and encrypts the memo with it. (Supercedes #30)

``` js
sender.getCondition(receiverPublicKey, ilpPacket:Buffer)
receiver.getFulfillment(receiverPrivateKey, finalTransfer)
// - Verify transfer has as much money as ilpPacket
// - Verify condition matches ilpPacket

// Alternative: sender-encrypted hashlock
sender.getCondition(receiverPublicKey, ilpPacket:Buffer)
receiver.getFulfillment(receiverPrivateKey, finalTransfer)
// - Verify transfer has as much money as ilpPacket claims
// - Verify condition matches ilpPacket
```

Open Questions:
- [ ] How to decide ILP header expiry for Passive case?
- [ ] How to decide source transfer expiry for Interactive & Passive cases?
- [ ] Do we have an equivalent to UDP/TCP ports (i.e. an application ID or something)
- [ ] Naming: Does it matter that we had a different meaning for UTP for a while? (Universal vs User-defined)

**Comment by r-marques** [comment]
Note that ed25519 is a public key digital signature system and its not intended to be used to encrypt.
There may be a way to reuse the key pair for encryption with a different crypto system, maybe curve25519, but I am not sure.

**Comment by emschwartz** [comment]
The [tweetnacl library](https://tweetnacl.cr.yp.to/) has a `secretbox` function that can be used for encryption, which uses the Ed25519 key for a Diffie-Hellman key exchange (explained [here](http://stackoverflow.com/a/13663945))

**Comment by emschwartz** [comment]
See https://github.com/interledger/rfcs/pull/76

@justmoon do you want to leave this open until we specify the "passive" version or close it now?

**Comment by emschwartz** [comment]
Here's an updated proposal for protocols that could comprise the Interledger equivalent of the Internet's Transport Layer.

**Interledger Transport Layer protocols may provide / define:**
- Details required for payment **setup**
- Payment and data **integrity** (reliability)
- Automatic payment **retry logic** (reliability, flow control)
- **Single payment vs streams** (connection-oriented communication, same-order delivery)
- **Non-repudiability**
- **Stateful vs stateless** receivers

Note that **multiplexing**, which is handled by the Internet's Transport Layer, is included in the core ILP because of subledgering (see https://github.com/interledger/rfcs/issues/132).

@justmoon had a good idea that we should not define an equivalent of UDP. Instead, developers should be able to define custom headers that travel with the ILP Packet. ILP Client implementations should allow raw access to ILP packet / sending transfers interface to allow custom protocols to be with the core Interledger Protocol directly. Connectors must forward packets with custom headers.

Here are some ideas for Interledger Transport protocols:

## Payment Request Protocol (formerly Interledger Payment Request)
- **Setup:** Recipient must provide sender with payment details for each payment. This includes account, amount, request ID, request expiry, condition, and other required headers/data that must be sent along with the payment
- **Integrity:** Fulfillment is the HMAC digest of the receiver's secret key and the payment details, including additional data carried with the payment. Recipient regenerates fulfillment from incoming prepared transfer details and only fulfills the transfer if the condition generated matches that of the transfer. Note that the recipient needs to HMAC a canonically-encoded version of the payment details, but this encoding is up to the recipient because the HMAC is only computed by them.
- **Single payment**
- **Retry logic:** Sender should retry until the request expiry given by the recipient
- **Non-repudiable**
- **Stateless receiver**

## Encrypted Key/Packet Protocol (alternative to Passive Transport described above)
- **Setup:** Sender gets recipient address and public key out of band. Payments are created by the sender without the recipient's involvement.
- **Integrity:** Fulfillment is the HMAC digest of a one-time key generated by the sender and the canonically-encoded payment details, including additional data. Sender encrypts the HMAC key, and potentially other payment data, using the recipient's public key. Recipient decrypts details, generates the fulfillment from the HMAC of the payment received, and only fulfills the transfer if its condition matches the one generated. Note that the sender and recipient need to use the same canonical encoding because both are generating the HMAC of the payment details.
- **Single payment**, but the sender may initiate any number of payments
- **Retry logic:** Need to define error codes to tell the sender when to stop sending payments
- **Repudiable**
- **Stateless receiver**

## Split Request Protocol
This may be useful in cases where the recipient knows it is more cost-effective or reliable for the sender to send multiple smaller payments instead of a single payment.
- **Setup:** Recipient generates payment request like in the Payment Request Protocol. Recipient also generates "splits", for example specifying that a request for $100 may be paid as 100 $1 payments and/or two payments for $80 and $20, etc. The splits may total to more than the requested amount, in which case the sender should only prepare splits totaling the amount they are willing to pay.
- **Integrity:** Fulfillment is generated from an HMAC of the receiver's private key and the full payment request. Recipient must check each incoming partial payment against an amount and "index" defined in the payment request. Partial payments with corrupted packets or insufficient amounts should be rejected.
- **Single payment:** Even though multiple payments are sent, they comprise a single logical payment
- **Retry logic:** Sender can retry splits before request expiry. Sender should only prepare payments totaling no more than the amount they are willing to spend. Partial payments that fail early may be discarded in favor of alternative splits, if provided.
- **Non-repudiable**
- **Stateful receiver:** Recipient must keep track of total amount prepared
- **(Un)Safety:** @sharafian and @dappelt pointed out this protocol may be unsafe for recipients on ledgers that do not support atomically fulfilling multiple transfers with the same condition. If each partial payment is fulfilled separately, there is a chance that part of the payment will expire after the recipient has already submitted the fulfillment once. In that case, the sender would end up with the fulfillment but the recipient would not get the full amount.

## Split Payment Protocol
(Credit to @sharafian)
- **Setup:** Combination of the Encrypted Key Protocol and the Split Request Protocol. Sender generates split payments.
- **Integrity:** Fulfillment is HMAC of sender-generated key and full payment details. Sender encrypts HMAC key using recipient's public key. Recipient must validate each of the prepared partial payments.
- **Single payment**, though the sender can initiate as many of these as they want
- **Retry logic:** Need error codes to tell the sender when to stop
- **Repudiable**
- **Stateful** receiver

## Nested/Repeated Request Protocol
Note this may not have enough of an advantage over having the recipient give the sender a batch of individual payment requests.
- **Setup:** Recipient generates payment details for a series of payments they want to request from the sender, gives details to the sender. Note that only a single condition needs to be provided.
- **Integrity:** Each fulfillment includes the condition of the next payment. Fulfillments should include HMACs of the payment details.
- **Stream** of payments
- **Retry logic:** ?
- **Non-repudiable**
- **Stateless** receiver only if the payment request includes the payment details of all the payments. Note this is simpler if the amount is repeated.

...and there may be more

cc @justmoon @sharafian @adrianhopebailie @sentientwaffle

**Comment by justmoon** [comment]
Just to officially add the one from the [HTTP-ILP proposal](https://github.com/interledger/rfcs/blob/d9d6c20750b381e877b907669be8efa53bf62937/0014-http-ilp/0004-http-ilp.md) to the list:

## Shared Secret Protocol
This is a generally useful protocol, since it only requires a one-time handshake to support one or more payments of arbitrary amounts or metadata. It also does not depend on any complex asymmetric crypto and sender and receiver can both be stateless.
- **Setup:** Sender and receiver start out with a static secret. Sender and receiver can communicate over some secure private channel, e.g. TLS.
- **Flow:**
  1. Sender generates a token using their secret and the receiver's hostname, e.g. `token = HMAC_SHA256(sender_secret, receiver_hostname)`.
  2. Sender requests the shared secret from the receiver, giving the token as an input.
  3. Receiver responds with the shared secret using their secret and the token, e.g. `shared_secret = HMAC_SHA256(receiver_secret, token)`. The receiver also provides an expiration date for the shared secret.
  4. The shared secret is used by the sender to generate conditions of the form `SHA256(HMAC_SHA256(shared_secret, payment_info))`. The payment information consists of `account`, `amount` and attached `data`.
  5. The shared secret is used by the receiver to generate fulfillments of the form `HMAC_SHA256(shared_secret, payment_info)`.
- **Integrity:** Fulfillment is generated from an HMAC of the payment information. Since the shared secret is only known to the sender and receiver, only the sender and receiver can 
- **Multiple payments:** The sender may send additional payments until the secret expires.
- **Retry logic:** Sender can retry payments at any time until the secret expires.
- **Repudiable:** The sender can't prove that the receiver acknowledged receipt of funds. This protocol is therefore suited for micropayments where discontinuing business is a sufficient sanction.
- **Stateless sender & receiver**

@emschwartz and I were chatting about this yesterday and it seems that you would use the Payment Request Protocol anytime you have an opportunity for the receiver to sign the payment request as part of an invoice (to get the non-repudiability benefit) and use the Shared Secret Protocol whenever you can't have non-repudiability anyways, because there is no signed invoice. If these two did become the two main supported protocols, it would be quite nice because they both just use SHA-256 and no fancy asymmetric crypto.

Both protocols could hash the same information for a given payment and differ only in the secret used (shared vs. provided by the receiver).

**Comment by sharafian** [comment]
> - Sender generates a token using their secret and the receiver's hostname, e.g. token = HMAC_SHA256(sender_secret, receiver_hostname).
> - Sender requests the shared secret from the receiver, giving the token as an input.
> - Receiver responds with the shared secret using their secret and the token, e.g. shared_secret = HMAC_SHA256(receiver_secret, token). The receiver also provides an expiration date for the shared secret.

How come the sender has to generate this token? Couldn't the receiver generate the secret and send it back when the sender requests it?

Also, if this is just `HMAC_SHA256(receiver_secret, HMAC_SHA256(sender_secret, receiver_hostname))`, how is it possible to expire it? Won't repeating the procedure to generate a new shared secret will yield the same result?

**Comment by justmoon** [comment]
> How come the sender has to generate this token? Couldn't the receiver generate the shared secret by generating a random value when the sender requests it?

Interesting. You're right that the token could just be generated by the receiver.

Where the idea of a sender-generated token came from is HTTP-ILP where the sender uses a token to access their balance. There it makes a lot of sense for that token to be sender-generated, rather than having two tokens (sender token + randomly-generated token by receiver) or having to store the receiver-generated token.

So I think it's useful to allow higher-level protocols to specify that the sender provides the token. But perhaps this could be optional?

Some things are the same even between Payment Request Protocol and Shared Secret Protocol: How information is formatted for hashing; how it is HMAC signed and how user-specified data is attached to an ILP packet.

Where Payment Request Protocol and Shared Secret Protocol differ is whether the receiver is willing to share their secret with the sender. And I guess the second decision is whether the receiver is letting the sender seed that secret.

> Also, if this is just HMAC_SHA256(receiver_secret, HMAC_SHA256(sender_secret, receiver_hostname)), how is it possible to expire it? Won't repeating the procedure to generate a new shared secret will yield the same result?

The expiration feature is only there to allow the receiver to change their `receiver_secret`. If the sender's and receiver's secrets don't change, then the shared_secret will be stable as well. (Which is what allows them to be stateless.)

**Comment by emschwartz** [comment]
You could have a stateless receiver with a rotating key if you did it on a
regular interval and included the day or week in the hmac that generates
the key.

>

**Comment by justmoon** [comment]
> > How come the sender has to generate this token? Couldn't the receiver generate the shared secret by generating a random value when the sender requests it?

> Interesting. You're right that the token could just be generated by the receiver.

Herpderp. Just realized that the token *has* to be generated randomly by the receiver. Otherwise, anyone can find out what the shared secret is just by passing the (public) token to the receiver and requesting a shared secret for it. Not very secret...

Long story short: The thing formerly known as token is always randomly selected by the receiver. It's actually part of the ILP address, so it never even appears as a separate value.

For protocols like HTTP-ILP the token is simply placed in the memo field.

I had implemented the broken way and then switched to this and it streamlines everything a bit and works great. Thanks for the suggestion, @sharafian.

**Comment by emschwartz** [comment]
After discussing with @sharafian @michielbdejong, our conclusion was that the main functionality provided by the Transport layer is ILP packet authentication and encryption and the Transport protocols can be categorized as follows:

Columns define **who generates the condition** and rows define **how the payment is authenticated**.

|  | Sender-Generated Condition | Receiver-Generated Condition |
|---|---|---|
| **Receiver Key** | Pre-Shared Key (PSK)* | Interledger Payment Request (IPR) |
| **Sender Key** | Encrypted Key Protocol (EKP) | ? |
| **Database** | n/a | Database Authenticated Payment (DAP) |

\* PSK was formerly known as the Shared Secret Protocol (SSP) and the Key Exchange Protocol (KEP)

**Comment by adrianhopebailie** [comment]
Can you expand on what you mean by:
>  how the payment is authenticated

**Comment by emschwartz** [comment]
When we originally came up with IPR we had the idea that you could use an HMAC of a receiver-generated key and the payment details as the condition fulfillment. That allows the receiver to be stateless but to check both that the IPR came from them originally and to check the integrity of the payment/packet (by regenerating the fulfillment from the payment details and seeing if it matches).

The idea of using an HMAC of the payment details as the fulfillment turned out to be quite useful, and it can be applied in a number of different flows. It ensures that the ILP packet cannot be tampered with in transit, because if a connector modifies it, the receiver won't fulfill the condition.

When using PSK, the sender and receiver first share a key. This could be done using Diffie-Hellman or just by having the receiver give the sender a shared secret over an encrypted and authenticated channel. The sender generates the payment details, then generates the fulfillment as the HMAC using the shared key and the payment details. They also encrypt the packet memo field using AES-CTR with the shared key. The condition is the hash of the fulfillment. When the receiver gets the incoming payment, they regenerate the fulfillment using the payment details and the same shared key and they fulfill the condition if it matches.

A similar idea can be used in the EKP if the sender has the receiver's public key. The sender generates a random key, uses it to generate the fulfillment as an HMAC of the payment details. The sender then encrypts the HMAC key using the receiver's public key and attaches the encrypted key to the payment. To fulfill the payment, the receiver decrypts the key and regenerates the fulfillment using the sender's key.

So, given this primitive, it makes sense to define the "Transport Layer" as a set of protocols that provide some combination of:
* fulfillment and condition generation logic
* payment details authentication
* memo encryption
* retry logic

**Comment by emschwartz** [comment]
Another variant that came from a conversation with @sharafian, @michielbdejong, @dappelt, @joaopedrovbs, @ivanseidel:

**Delayed Key Protocol (DKP, i.e. Payments with "Undo Send")**
1. Sender uses a random key to HMAC the payment details for the condition. Sender sets the expiry ~30 seconds in the future.
2. Sender prepares payment.
3. Receiver is notified of incoming payment and confirms receipt of the held funds with the sender out of band.
4. Sender transmits HMAC key to the recipient out of band.
5. Recipient fulfills transfer.

This would enable a flow where the sender's device could automatically tell the recipient the key after 10-30 seconds, giving the sender a couple of seconds in which they could cancel the payment in case there was a problem. This is inspired by [Gmail's Undo Send](https://www.nytimes.com/2015/06/24/us/gmails-undo-send-option-can-help-end-email-embarrassment.html) feature and M-Pesa also has something similar. It's a simple idea that prevents a lot of mistakes.

This might depend on https://github.com/interledger/rfcs/issues/155, because right now most connectors wouldn't accept a longer hold duration.

**Comment by emschwartz** [comment]
I think this can be closed now
