### ISSUE TITLE
[Question] Using STREAM to transfer data

### ISSUE THREAD

**Issue by dora-gt** [interledger/rfcs#434]
- What is the best case to use STREAM for transferring data?
    - We can transfer data without STREAM because we know the counter endpoint.
    - What is the essential difference between using STREAM and using the other ways for transferring data?

**Comment by emschwartz** [comment]
Sorry for the slow response! That is a very good question and I'm not sure we know the exact answer now.

The most straightforward use case is sending a memo, receipt, or some other information directly related to the payment.

The main reason we put this in was because it seemed like a useful building block to provide to application layer protocol designers. You can use it for really small and simple things like getting explicit acknowledgement when a stream is listening and ready to go like Cog does [here](https://github.com/coilhq/cog/blob/4707dc3b3ac137ff446dced368eaa6f54d222098/src/listener.js#L56-L57). Or, you could build much more elaborate things on top, like sending whole files over it.

Right now, the implementations of the various protocols in the ILP stack aren't really designed for sending large amounts of data, but we didn't want to preclude that possibility in the future. At some point it would be interesting to try implementing TLS over ILP so that you could start a whole ILP interaction just with someone's ILP address and certificate (anyone interested in running the first ILP Certificate Authority? 😉)

**Comment by dora-gt** [comment]
Thank you for the response.

I can now imagine that, using STREAM, the payment and data can be easily combined. I think it's easier than the other ways that do it with separated sockets though it is possible.
