### ISSUE TITLE
[Question] How to compose STREAM packet

### ISSUE THREAD

**Issue by dora-gt** [interledger/rfcs#435]
- How to compose STREAM packet.
    - For example, I have (A and B) endpoints on a connection and 2 streams on it.
        - A sends 100 [XRP] to B on a ILP Prepare packet that contains 4 frames.
            - A money frame and a data frame for stream "alpha", share 50%
            - A money frame and a data frame for stream "beta", share 50%
        - B wants to decline "alpha" but wants to accept "beta".
    - Then what happens?
        - The frames is prepared on the same condition.
        - Can B decline only "alpha"?

**Comment by emschwartz** [comment]
If the receiver rejects a packet, it rejects all of the frames contained in it.

We could add a recommendation to the spec like [this one](https://quicwg.github.io/base-drafts/draft-ietf-quic-transport.html#rfc.section.7.18) from QUIC:
> Note that when data from multiple streams is bundled into a single QUIC packet, loss of that packet blocks all those streams from making progress. An implementation is therefore advised to bundle as few streams as necessary in outgoing packets without losing transmission efficiency to underfilled packets.

**Comment by dora-gt** [comment]
I see.

I'm curious about the succeeding procedure.
A should know...
- alpha was rejected.
- beta was qualified but rejected because of the other stream (alpha).
and resend a packet for beta again somehow.

It may be application layer problem though. The strategy how many frames should be in a ILP packet is difficult.

**Comment by emschwartz** [comment]
That actually is a transport-layer (or transport implementation) concern. It's definitely one of the trickier parts of this.

The two types of frames that might cause a packet to be rejected are the `StreamMoneyFrame` and `StreamDataFrame`. If the receiver rejects it because of a money frame, they should probably send back a `StreamMaxMoneyFrame` and if it's rejected because of a data frame, they should send back a `StreamMaxDataFrame`.

**Comment by emschwartz** [comment]
If the receiver doesn't respond with any type of frame, the sender should just resend that one.

The way the implementation handles this is that each side keeps track of the limits of the other side. When one is loading up packets to send, it checks whether each stream has money and/or data to send, and if the other side is willing to receive more, and sends off packets accordingly. Stream Max frames are used just to update the state representing the other sides limits.

**Comment by emschwartz** [comment]
I think the packet should only be rejected if:
- There is money for a stream that exceeds its limit
- There is data for a stream that exceeds its limit
- There is money or data for a stream that is already closed
- The packet contains an invalid frame (I think this should actually cause the connection to close)

If the receiver doesn't want the data for some other reason, that can be handled on the application layer. For example, if you implemented a request/response protocol on top of STREAM, the recipient of the data could respond to a request with an error. However, that would not be done at the level of fulfilling or rejecting packets, that would just be application data that the receiver would send back to the sender.

Packets should only be rejected because of concerns internal to the STREAM protocol

**Comment by dora-gt** [comment]
So, what about this case?

- A web application API
  - Accepts `uint` from 0 to 100 that represents an ID
  - Returns some data for the ID
- A user sends a request
  - Contains `uint` of 200
  - Exceeds limit (200 is over 100)

I think this is application layer concern, but this should be rejected and refunded, isn't it?

**Comment by emschwartz** [comment]
The application would have set the `receiveMax` to 100 units, so any packets that would exceed that limit would be rejected automatically. The sender's STREAM module would know not to send more than that.

**Comment by dora-gt** [comment]
Ah I see. Maybe this use case is not suitable for STREAM 🤔
If the request consists of multiple input fields, the request cannot be rejected automatically. 
Perhaps I should learn STREAM + SPSP, and how they handle the entire business transaction.
