### ISSUE TITLE
Support for unidirectional peering relationships in asym plugins

### ISSUE THREAD

**Issue by kincaidoneil** [interledger/rfcs#443]
### Rationale

The current asym client/server plugins do not support sending strictly unidirectionally, however, there are use cases where this is either necessary or makes the interaction faster/cheaper:

- The receiver may not have any of the asset in which they're being paid (such as in the case of a decentralized Shapeshift where a user is essentially sending to themselves)
- In the case of cryptocurrencies where on-chain transactions are slower and more expensive than XRP (e.g. Ethereum), if the interaction between user & connector is known to be unidirectional, there's no reason to incur the additional time/cost of opening an unnecessary payment channel
- If a receiver has no preexisting relationship with a connector that's sending to them (or, maybe they had a relationship but the payment channel was recently settled & closed), from the receiver's perspective, it may make more sense for the *sender* to front the connector's cost of opening a payment channel with the receiver, rather than the receiver having to front the cost, only to get paid by the connector

### Proposal

- Multi-plugins should accumulate a balance for an account, up to some threshold/the cost of an on-chain transaction
- After hitting that threshold, it would open an outgoing payment channel to the client, subtracting the cost from its balance
- The client would have two options to hit that threshold with the server:
  1. Open a channel to the server and send a claim to front the server's cost of opening a channel back to the client (current implementation)
  2. Have the cost fronted from the balance you are owed by the server: in this case, you would continue fulfilling packets even though you weren't being paid right away (up to some limit, of course), enabling the server to accumulate enough of a balance to eventually open a channel to you

I believe this is in the same vein as @sharafian's Siren, but we propose that this should be supported in all plugins underpinned by payment channels.

For client plugins, they'd still open a channel to the server by default, but, we propose there could be a constructor option (e.g. `receiveOnly`) to prevent the client from opening a payment channel. From there, it would likely only require minor changes to the plugin. If you wanted to use the unidirectional mode, you'd just need to have the balance logic wrapping the plugin configured to support fulfilling packets up to some reasonable limit.

We built the refactor of the Ethereum asym plugins to support this model, and are very interested in feedback on this approach, and the possibility of other plugins supporting it.

(Credit to @emschwartz and @karzak)

**Comment by adrianhopebailie** [comment]
As discussed on some of the recent community calls and at the summit there is support for this.

A few notes:
> If a receiver has no preexisting relationship with a connector that's sending to them (or, maybe they had a relationship but the payment channel was recently settled & closed), from the receiver's perspective, it may make more sense for the sender to front the connector's cost of opening a payment channel with the receiver, rather than the receiver having to front the cost, only to get paid by the connector

This is very similar to how cross-border payments work today. The sender will usually designate who is going to cover the fees (sender, receiver or both). This does beg the question if there needs to be a 
way for the receiver to express this to the sender in the setup protocol.

Example: A client connects to a server and has a channel for sending to that server but not for receiving. The cost for the server to create a channel is 0.1 ETH. The client is requesting a payment from some sender for 5 ETH. How do they ensure that they actually get sent 5.1 ETH.

We should think about this in the context of protocols like SPSP and STREAM and whether the setup changes at all.

> Multi-plugins should accumulate a balance for an account, up to some threshold/the cost of an on-chain transaction

This is not dissimilar to payout schemes that have a minimum payout threshold like the Google Play Store. We need to give this some standard name so that as a client I can "shop around" for servers and get a consistent view of what my costs will be.

The standard behaviour should be that when a client connects, the server notifies them of the **"minimum payout threshold"**. The client can then either pay that to the server immediately and then the server should create the channel or the client will expect the server to begin forwarding packets to the client and when these add up that threshold the client should expect the server to establish the channel.

Today the **"minimum payout threshold"** on most servers is 0, but it would make sense for it to be 12 drops on XRP-settled servers as an example, or maybe even 24 to cover the cost of closing the channel.

Obviously this all assumes that clients must trust servers to track this value correctly and act upon it when appropriate but I think this is fair given that the server is a commercially motivated service-provider who is not likely to stay in business long if they mess this up.
