### ISSUE TITLE
Mismatch between RFC and implementation, BTP

### ISSUE THREAD

**Issue by dora-gt** [interledger/rfcs#445]
In the [BTP RFC](https://github.com/interledger/rfcs/blob/master/0023-bilateral-transfer-protocol/0023-bilateral-transfer-protocol.md#overview), the structure of BTP packet is explained as the below.

1. Type ID
2. Request ID
3. Packet Specific Data
4. Sub-Protocol Count
5. Sub-Protocol Data

While the implementation is like the below, not having `packet specific data`. `writeProtocolData` just writes out 1) sub-protocol count, 2) sub-protocol data.
[btp-packet/index.js#L125](https://github.com/interledgerjs/btp-packet/blob/master/index.js#L125)

We need to make it clear which is correct, or, if it is correct, I think RFC should be updated to avoid leading to misunderstand.

**Comment by adrianhopebailie** [comment]
I would recommend that the RFC be corrected to reflect reality if the implementation is different.

@sharafian can you provide some insight into which BTP packet types and sub-protocols are now widely used so we can document these. We should avoid documenting stale code that is no longer used.

**Comment by sharafian** [comment]
Currently, the plugin BTP is only making use of `MESSAGE` and `RESPONSE` packets. `MESSAGE` and `RESPONSE` have no packet specific data, which is why it goes straight to sub-protocol count.

**Comment by dora-gt** [comment]
I see. So, maybe RFC is wrong (...or at least misleading). I checked [ASN.1 definition](https://github.com/interledger/rfcs/blob/master/asn1/BilateralTransferProtocol.asn) it reflects what you told. So I suggest amending RFC according to the ASN.1. I'll try.

**Comment by adrianhopebailie** [comment]
@earizon the protocols operate at different layers of the stack. An ILP error should not be carried in a BTP error.

**Comment by earizon** [comment]
@adrianhopebailie It's weird because the BTP errors can be mostly mapped to ILPv4 errors.

T00 UnreachebleError can be mapped to T01 Peer Unreachable
F01 InvalidFiledsError can be mapped to F00 Bad Request
F03 TransferNotFoundError can be mapped to F06 Unexpected Payment
F08 InsufficientBalanceError can be mapped to F04 Insufficient Liquidity

F00 NotAcceptedError, F04InvalidFulfillmentError, F06 AlreadyRolledBackError, F07AlreadyFulfilledError have no equivalent in 0027 ILPv4 but can be added to reuse in BTP and non-BTP protocols (ILP-over-HTTP).

Only the F05 DuplicateIdError looks to be BTP only related. Also it could make sense to add some other for the case when BTP initial session authentication fails.

Don't you think there is an overlap, even if they are on different layers?.

When I implemented the HTTP-over-ILP plugin (https://github.com/everis-innolab/ilp-everconnector/blob/master/src/main/java/org/everis/interledger/plugins/ILPOverHTTPPlugin.java) I just limited to reuse standard ILPv4 exceptions (See function __respondWithError) and could manage to connect to the testnet-of-testnet and receive pertinent feedback in case of error. To me there is no much difference between ILP-over-HTTP and BTP (appart of the "low-level" details HTTP vs websocket transport). In fact the ILP-over-HTTP rfc proposal (https://github.com/interledger/rfcs/blob/de237e8b9250d83d5e9d9dec58e7aca88c887b57/0000-ilp-over-http.md) indicates to return ILPv4 error codes in the ILP-Error-* headers.

**Comment by dora-gt** [comment]
hmmm, BTP probably should not know about its sub-protocols.
If we add BTP error codes for sub-protocols that are added, it breaks the **open/closed principle**.
This is just my own opinion.

**Comment by dora-gt** [comment]
hmmm, BTP probably should not know about its sub-protocols.
If we add BTP error codes for sub-protocols that are added, it breaks the **open/closed principle**.
So I would suggest either:
1. A BTP error is just for a BTP layer error (link layer error)
   - A BTP packet will not be an error even if sub-protocols contain errors
2. A BTP error is a general sign of a BTP layer error or that sub-protocols may contain error
   - Never duplicate error definitions on BTP layer

Am I wrong? This is just my own opinion.

**Comment by emschwartz** [comment]
I think the reason BTP seems so weird is that about 90% of its purpose was changed between BTP 1.0 and BTP 2.0 (which accompanied the switch from ILPv1 to ILPv4). Originally, the link layer was expected to do a lot more -- it had the transfer object, which included the amount, condition, expiry, etc and so it also needed more in the way of error messages. However, when the amount and condition and such moved into the ILP layer, we also copied most of the error codes to that layer and overall BTP lost a lot of its purpose.

Right now, BTP is basically being used as a binary RPC protocol over WebSockets. I doubt we'll want to keep it around forever, but right now it seems easier to roll with it, accept the weirdness, and get things working.

All of that said, I agree with @dora-gt that whatever BTP errors there are should just be for the BTP layer.
