### ISSUE TITLE
RFC-4: Events `receive`, `fulfill_execution_condition`, `reject` -> `transfer_{prepare,execute,reject}`

### ISSUE THREAD

**Issue by emschwartz** [interledger/rfcs#45]
Proposal: replace `receive`, `fulfill_execution_condition`, and `reject` with `transfer_prepare`, `transfer_execute`, `transfer_reject`.

Right now our event API leads to unnecessary complication on the part of the user of the plugin (client or connector).

Let's say you're a receiving client trying to check when you receive money. Right now you need to listen for both the `receive` and the `fulfill_execution_condition` events. You need to check whether a transfer you get from the `receive` event has an `execution_condition`. If not, you have actually received money. If the transfer does have a condition, you need to recognize that you have not received money but only a notification of funds being held. You only know a Universal payment (with holds) is completed when you get a `fulfill_execution_condition` event. You can't only check the `fulfill_execution_condition` event though because you might get money from a transfer with no condition.

Since any user of the plugin will immediately want to know the state of a transfer it gets, and since the plugin is in the best position to know what state it is in (depends on the details of the ledger), the plugin should provide explicit events for these different states.

**Comment by emschwartz** [comment]
cc @justmoon @sentientwaffle

**Comment by sentientwaffle** [comment]
The makes deleting the `expiresAt` from the `transfer` object when it is executed (https://github.com/interledger/js-ilp-plugin-bells/pull/6) unnecessary.

**Comment by justmoon** [comment]
> Let's say you're a receiving client trying to check when you receive money. Right now you need to listen for both the `receive` and the `fulfill_execution_condition` events.

That's not ideal. If you're the receiving client you're the one who has to **post** the fulfillment. The way it should work is: You would only listen to `receive`. If the transfer has a condition, you post the fulfillment and then process the payment and if it doesn't, you just process the payment.

I'm going to assume for simplicity that we're going to get rid of cancellation conditions. (#48)

##### Example (Receiver)

```js
client.on('receive', (transfer) => {
  // Check amount, etc.
  if (transfer.condition) {
    // Try to fulfill the condition or throw if unable
  }
  // Process the payment
})
```

##### Example (Connector)

```js
client.on('receive', (transfer) => {
  if (transfer.condition) {
    // Check if expiry window is sufficient
  }
  // Forward payment (same condition or lack thereof)
})

client.on('send_fulfill', (transfer, fulfillment) => {
  // Forward fulfillment to transfer.noteToSelf.source_ledger
})
```

Currently, the receiver needs only `receive` and the connector needs `receive` to pass forward a transfer (with or without condition) and `fulfill_execution_condition` to pass back a fulfillment.

### Simple API

This would be the simplest possible API which covers all common use cases (sending, connecting, receiving):

-> `receive(transfer)` - Someone did a send() to me
-> `send_fulfill(transfer, fulfillment)` - A transfer I sent got fulfilled
-> `send_reject(transfer)` - A transfer I sent got rejected

### Advanced API

This could be used for more advanced use cases like logging transfers

-> `transfer_prepare(transfer)`
-> `transfer_execute(transfer, fulfillment?)`
-> `transfer_reject(transfer)`

Or:

-> `transfer_update(transfer, status:String, fulfillment?)`

----

We want to minimize the complexity of the ledger plugins, so having two APIs seems not ideal. Perhaps one solution would be to have the ledger plugin API expose only `transfer_update` and `ilp-core` automatically add the other events from that. At a mimimum, the `receive` event I think is very useful - see the pseudo-code above.

**Comment by adrianhopebailie** [comment]
It seems like the ledger only needs to emit 3 different events.
(Assume this is for the life-cycle of a transfer from internal accounts A -> B held on the basis of condition C)

1. `funds_on_hold` (i.e. Incoming transfer request received requesting transfer from A -> B with condition C specified in the transfer)
1. `funds_released` (i.e. The transfer that was on hold from A -> B has been released - because the ledger received f(C) OR an incoming transfer request from A -> B was submitted with no condition)
1. `transfer_reversed` (i.e. Transfer from A -> B has been rolled back and the funds have been returned to A either due to a timeout or at the request of B which has declined the incoming transfer)

The owners of the accounts A and B would subscribe to all 3 events and that would be enough for them to track everything they need to know as client or connector.

All events would have data attached to them, including the identifiers of the local `from` (A) and `to` accounts (B) and the ILP packet header data (ILP address of final recipient, amount to be paid to final recipient, timeout, condition (C))

The `funds_released` event would have the fulfilment (f(C)) instead of the condition (C).

The `transfer_reversed` event would have a reason (TIMEOUT, DECLINED_BY_RECEIVER)

**Comment by justmoon** [comment]
> because the ledger received f(C) OR an incoming transfer request from A -> B was submitted with no condition

These are two different events - that's why you end up with that "OR" in your description.

1. Optimistic send (=transfer_execute)
2. Universal send (=transfer_prepare)
3. Universal fulfill (=transfer_execute)
4. Optimistic/Universal reject (=transfer_reject)

(And all of these apply to incoming and outgoing transfers.)

`receive` is grouping 1+2 (incoming only) and `transfer_execute/funds_released` are grouping 1+3.

Grouping 1+2 seems more useful to me than grouping 1+3, because you'll want to handle universal payments when they're prepared, not when they're executed. 

Perhaps for the low-level ledger plugin API it would be useful to consider making all four events separate and not grouping any of them, e.g.:

1. `transfer_simple` - Optimistic send
2. `transfer_prepare` - Universal send
3. `transfer_execute` - Universal fulfill
4. `transfer_reject` - Optimistic/Universal reject

**Comment by MatthewPhinney** [comment]
> Currently, the receiver needs only receive

@justmoon I don't follow this. The receiving client also needs `fulfill_execution_condition`, because they must know when the transfer has actually executed, so they can notify the appropriate parties.

I like @emschwartz's idea of explicitly providing the transfer state in the event. In this case, the client can simply check to see if the event is for an incoming or outgoing transfer and take the appropriate course of action.

**Comment by justmoon** [comment]
> @justmoon I don't follow this. The receiving client also needs fulfill_execution_condition, because they must know when the transfer has actually executed, so they can notify the appropriate parties.

They are the ones who submit the fulfillment - if they successfully did that they can notify the appropriate parties. See my pseudocode above for an example.

**Comment by MatthewPhinney** [comment]
> They are the ones who submit the fulfillment - if they successfully did that they can notify the appropriate parties

In the context of atomic mode this is not necessarily true. The receiver may successfully submit the fulfillment to the notary, but the notary may not pass it to the ledger (for whatever reason). In this case, the receiver should not consider the payment complete until the ledger sends a notification indicating that the transfer has actually executed. Even if the receiver puts the fulfillment directly to the ledger, it seems more robust to actually have an explicit ledger notification informing the receiver that the payment has executed.

**Comment by adrianhopebailie** [comment]
My view on this is that clients/connectors care about events that affect their local account on the ledger. Therefore I liked the idea of the advanced API from @emschwartz .

We could simplify this down to 2 events: `funds_in` and `funds_out` but that would make it less elegant because we'd not always have a `from` and `to` account (the `to` account would sometimes be the hold account and then it's difficult to know who it is being held for.).

>These are two different events - that's why you end up with that "OR" in your description.

>1. Optimistic send (=transfer_execute)
>2. Universal send (=transfer_prepare)
>3. Universal fulfill (=transfer_execute)
>4. Optimistic/Universal reject (=transfer_reject)

I don't see the value, at the basic ledger interface level, of distinguishing between optimistic and universal modes. Technically a ledger doesn't need to know the difference. It just needs to look at the condition provided with any transfer request and either put the transfer on hold (pending the fulfillment of the condition) or execute it (if the condition is null).

It should be possible for the event handler to determine the difference by looking at the ILP Header data fields and other event parameters. i.e. If condition is null: "Optimistic Send" else if fulfillment is not null "Universal Fulfill".

My assumption is that all events carry the ILP Header that was submitted with the transfer request and in addition may have a fulfillment or a rejection reason.

Where would you get the rejection reason from:
`-> transfer_update(transfer, status:String, fulfillment?)`

I'd make it the job of higher level components like the client to emit more colorful events. The ledger events should be simple but I don't see the value in combining them all into a single status event with a string name. TBH, that's just personal style prefs.

I agree with @MatthewPhinney that I'd want (as the receiver) to get an event that indicates I have been paid after I submit a fulfillment. This allows submission of fulfillments to be done asynchronously (which I think is desired) and potentially in a completely parallel process so that the heavy processing required can be offloaded to other systems even.

**Comment by justmoon** [comment]
@MatthewPhinney Atomic mode requires shared trust, so it makes more sense that Atomic mode would be used internally by groups of nodes (e.g. a bank consortium which uses a specific vendor's proprietary solution) and would be an internal protocol extension. Whether to do this is off-topic here, but we should not let Atomic mode affect our choice.

> I'd make it the job of higher level components like the client to emit more colorful events.

Agreed. :+1:

> I don't see the value, at the basic ledger interface level, of distinguishing between optimistic and universal modes. Technically a ledger doesn't need to know the difference.

:-1:

1. Sender->Receiver (direct)
2. Sender->Hold (prepare)
3. Hold->Receiver (fulfill)
4. Sender->Sender (reject)

These are four different cases, four different events. Combining two of them into one seems arbitrary to me. You're combining 1+3, but may just as well combine 1+2. Since these events are emitted for both incoming and outgoing transfers we could be the sender or the recipient.

I think the only reason combining 1+3 feels natural is because five-bells-ledger happens not to distinguish between them and we have a heavy cultural bias from using five-bells-ledger a lot. As an example, I've recently built a streaming ledger and for that ledger, these four events are all separate and have nothing whatsoever to do with each other.

> I don't see the value in combining them all into a single status event with a string name. TBH, that's just personal style prefs.

:+1:

**Comment by adrianhopebailie** [comment]
> These are four different cases, four different events. Combining two of them into one seems arbitrary to me. You're combining 1+3, but may just as well combine 1+2. Since these events are emitted for both incoming and outgoing transfers we could be the sender or the recipient.

By that reasoning perhaps we should add a fifth (and possibly sixth case). A rejected transfer could be rejected after 1, 2 or 3 and we don't differentiate. Should we?

Example 1:
* Event 1 is emitted after sender submits transfer.
* Receiver rejects transfer (perhaps it can't route the payment)
* Event 4 is emitted but this is actually a Reciever -> Sender

Example 2 (maybe avoided if submission of transfer is synchronous but that seems like a bad assumption):
* Event 2 is emitted after sender submits transfer.
* Ledger can't perform hold (perhaps it realises it won't be able to evaluate the fulfillment)
* Event 4 is emitted but this is actually a Hold -> Sender

Example 3 (maybe not a realistic situation because receiver has submitted fulfillment so we should assume won't reject transfer):
* Event 3 is emitted after fulfillment is submitted by receiver.
* Receiver rejects transfer (not sure if this is realistic but I'm nervous to make that assumption)
* Event 4 is emitted but this is actually a Reciever -> Sender

I think the event emitted by example 1 and 3 could be the same (transfer rejected by receiver) especially since example 3 seems very unlikely.

So a possible change would be to split event 4 into:
4. Rejected by Ledger
5. Rejected by Receiver

Some questions to ask:
1. Should B know about a transfer from A -> B that was rejected by the ledger?
2. Is it sufficient to differentiate between these based on the reason?

In terms of combining 1 and 3 it comes down to deciding who is best placed to differentiate between the two events:
1. Do we put the onus on the ledger needing to know which event to emit or 
2. Do we assume the the client/connector can differentiate by looking at the meta-data

Asked differently, does the ledger always know the difference between 1 and 3? If so then we should have separate events. (I think the answer is yes)

Some other thoughts:

3 is really a specialization of 1 with the addition of a fulfillment in the event meta-data. The consumer of both events still wants to know who the sender and receiver were (i.e. the fact that 3 is a Hold -> Receiver is not important, the  Receiver cares who the original Sender was and expects to see that in the meta-data.

If you modeled this I'd say all these events share the same interface (`LedgerEvent`):

-> local `from` account of sender
-> local `to` account of receiver
-> local `amount`
-> destination `ILP address`
-> `destination amount`

The `SimpleLedger` (doesn't do holds) interface emits events 1, 4 and 5 only
The `HoldSupportingLedger` extends `SimpleLedger` and emits events 1, 2, 3, 4 and 5

Event 1 is simply an implementation of `LedgerEvent` called `DirectTransferEvent`
Event 2 extends `LedgerEvent` to define `PreparedTransferEvent` with the following additional members
-> `condition` (nullable)
-> `timeout`

Event 3 extends `LedgerEvent` to define `FulfilledTransferEvent` with the following additional members
-> `fulfilment`

Event 4 extends `LedgerEvent` to define `TransferRejectedEvent` with the following additional members
-> `rejection reason` (assuming that this has enough info for the consumer to know who rejected the transfer - ledger or receiver)

Final question(s), to address something @MatthewPhinney said:

* Do we need an event 5 and 6 which deal with fulfillment and cancellation as a result of signals from a notary?
* When a transfer is fulfilled because a notary indicated it should be is it enough to simply provide the fulfillment or do we need additional meta-data about the notary etc?
* Will there always be a fulfillment or could the notary signal a ledger to fulfill the transfer through some other mechanism?

**Comment by MatthewPhinney** [comment]
@justmoon Yeah, atomic mode may be off topic here. I only brought it up as an example of why the receiver may want to listen for an event signaling that the funds have moved from hold to the receiver account. I can see this being useful in universal mode also, but if our design intention is to have the receiver only listen for a transfer prepared event and assume the transfer has executed once they successfully put the fulfillment, that's fine with me.

> I think the only reason combining 1+3 feels natural is because five-bells-ledger happens not to distinguish between them and we have a heavy cultural bias from using five-bells-ledger a lot.

👍

**Comment by MatthewPhinney** [comment]
Actually, thinking this through a bit more, it would be useful for the receiving client to have the option of listening for an event indicating that the transfer has executed. Similarly, it would be useful for the sending client to be able to listen for an event indicating that the transfer has been prepared (not possible in the current implementation).

**Comment by adrianhopebailie** [comment]
@MatthewPhinney my assumption is that anyone connected to the ledger can subscribe to any event where their local account is either the `to` or `from` account

**Comment by MatthewPhinney** [comment]
That sounds good. We just need the plugin to emit these events.

**Comment by justmoon** [comment]
Discussed with @bensharaf. 

Here's what we came up with:

### Events

On the receiver side:

* `incoming_transfer` - A transfer with no execution condition has been received
* `incoming_prepare` - A transfer with an execution condition has been prepared
* `incoming_fulfill` - You have fulfilled a transfer with an execution condition
* `incoming_reject` - You have rejected a transfer with an execution condition
* `incoming_cancel` - An incoming transfer with an execution condition has been cancelled by the ledger (e.g. due to a timeout)

On the sender side:

* `outgoing_transfer` - A transfer with no execution condition has been sent
* `outgoing_prepare` - You have prepared a transfer with an execution condition
* `outgoing_fulfill` - The recipient fulfilled a transfer with an execution condition
* `outgoing_reject`- The recipient has rejected a transfer with an execution condition
* `outgoing_cancel` - An outgoing transfer with an execution condition has been cancelled by the ledger (e.g. due to a timeout)

### Methods

* `send(transfer:OutgoingTransfer)` - Create and submit a new outgoing transfer; throw an exception if the transfer could not be successfully prepared
* `fulfillCondition(transferId:String, fulfillment:Buffer)` - Fulfill an existing incoming transfer; throw an exception if the transfer could not be successfully fulfilled
* `reject(transferId:String, rejectionReason:Buffer)` - Reject an existing incoming transfer; throw an exception if the transfer could not be successfully rejected

### Rationale

* Events for incoming and outgoing transfers should be different since you almost never need to handle both at once.
* Splitting recipient rejection and ledger rejection as @adrianhopebailie suggests makes sense. Rejection by the recipient indicates a problem with the transfer whereas a timeout would indicate a problem with the recipient.
* Splitting execution for transfers with and without condition makes sense, because sometimes you want to handle `incoming_prepare` and `incoming_transfer` the same while other times you care about `incoming_fulfill` and `incoming_transfer`. It's easier to listen to two events than to choose one of those combination and making some users tease the events apart.
* We considered removing events that indicate you yourself did something, e.g. `outgoing_transfer`, `incoming_fulfill`. But we decided to keep them since you may want to react to events triggered by clients you are running in separate processes.

**Comment by adrianhopebailie** [comment]
>  incoming_reject - You have rejected a transfer with an execution condition

Why is this explicitly "with an execution condition"?

**Comment by emschwartz** [comment]
@adrianhopebailie If there isn't an execution condition you would have already received the money

**Comment by adrianhopebailie** [comment]
@emschwartz But you can still reject it. 

I don't think we must force a receiver to do a new transfer back to the sender if they want to reverse a transfer they received and don't want.

I know that seems unlikely but at this level we must support all technically possible scenarios (even if they don't make business sense). Business logic around if and when to reject a transfer is not defined at the protocol level.

**Comment by emschwartz** [comment]
What you're saying is implemented in five-bells-ledger as the "authorized credits" feature, where credited accounts must authorize transfers as well as debited ones. At the moment this is not part of the ledger abstraction layer provided by the plugin interface. If you want to propose adding that feature to this abstraction layer I'd suggest that should happen in a different issue.

**Comment by emschwartz** [comment]
The reason I think it's a separate feature is that you would need to add the "accept transfer" function to the interface as well as the event you're talking about. This may be a good addition, but we should also be somewhat hesitant to add too much to the abstraction layer, especially if many ledgers will not actually implement this feature.

**Comment by adrianhopebailie** [comment]
> you would need to add the "accept transfer" function to the interface as well as the event you're talking about

Yep, you would.

The problem with leaving anything out of the interface is that you limit what someone can do in their implementation. Rather have events and methods that aren't used than force implementations to come up with hacks to somehow get the functionality they want through a limited interface.

The only good reason to not put something in an interface is if it just "feels" like something someone might want to do but you don't actually have a use case. In this case we do, we already have an implementation that does this.

If we break down the interface it has two sets of functionality; supporting optimistic and universal mode payments. The events are basically all of the possible state changes of a transfer in either mode. That's how we should think of the design, not in terms of what consumers may or may not do with the API.

**Comment by justmoon** [comment]
> I don't think we must force a receiver to do a new transfer back to the sender if they want to reverse a transfer they received and don't want.

That is a valid use case, but we're finding it sometimes hard to justify because it's causing a lot of extra complexity to be added.

Checking with the receiver in the flow of an optimistic payment is extremely awkward, high latency, fragile. Credit authorization before transfer preparation in universal mode has similar issues.

@bensharaf had a solution to this dilemma which I really like: Just make a ledger where only the receiver can post fulfillments.

If we also assume that this ledger will let you turn off / disallow incoming optimistic payments - then you can prevent unwanted incoming payments without adding any complexity to the API discussed here, without adding any latency and extra roundtrips or even adding much complexity to the ledger or ledger plugin.

If I don't want to receive unexpected funds, I just turn off optimistic mode payments on my account and only post fulfillments if I was able to handle the payment.

That doesn't cover all possible use cases for credit auth, but it does cover 99% at 1% of the complexity, so I'd argue that's what we should do for now.

**Comment by adrianhopebailie** [comment]
I worry that we are looking too closely at implementation details in defining this interface. I see this whole thing as a sequence of async method calls and events.

The complexity you talk of is all in the implementation of the ledger and connectors. That shouldn't influence the design of the interface between them unless the design is forcing them to add complexity to support a specific use case.

Example, for this flow:
1. Sender -> Ledger.sendTransfer()
2. Ledger -(outgoing_transfer)-> Sender
3. Ledger -(incoming_transfer)-> Receiver
4. Receiver -> Ledger.rejectTransfer()
5. Ledger -(incoming_reject)-> Receiver
6. Ledger -(outgoing_reject)-> Sender

If the ledger rejects the transfer (because optimistic payments have been turned off) then the flow should be:
1. Sender -> Ledger.sendTransfer()
2. Ledger -(incoming_reject)-> Receiver
3. Ledger -(outgoing_reject)-> Sender

i.e. The methods and events shouldn't hold any business logic semantics. How they are combined is dependent on the business logic.

A good way to make this extensible is to them allow the reasons codes to be extended by the implementation so that a ledger can signal specific things like "Rejected because you have turned off optimistic payments" which relate to that ledger's features without breaking the contract of the interface.

**Comment by emschwartz** [comment]
Continuing the discussion about authorized credits on https://github.com/interledger/rfcs/issues/64

**Comment by emschwartz** [comment]
Closed by https://github.com/interledger/rfcs/commit/c4ef7fc09e4e1a9743ba6bd02f09a94930584391
