### ISSUE TITLE
Proposal: "payments" -> "transfers"

### ISSUE THREAD

**Issue by emschwartz** [interledger/rfcs#50]
Earlier when we actually had `Payment` objects, which contained multiple `Transfer` objects corresponding to different ledgers, it made sense to distinguish between local "transfers" and interledger "payments". Now that we do not have `Payment` objects anymore, we should stop using the term "payments". "Payments" are a loaded term for many people, and they also imply sending currency, which Interledger is not limited to.

I would propose that we talk about any sending of assets as a "transfer". If we need a distinction between local and interledger sends, I would propose that we say either "local transfer" or "interledger transfer".

**Comment by emschwartz** [comment]
cc @justmoon @adrianhopebailie @diminator

**Comment by adrianhopebailie** [comment]
> I would propose that we say either "local transfer" or "interledger transfer".

I understand the motivation but I still like payment when talking about an "Interledger Transfer". The end-to-end transaction is a payment in my opinion.

I think trying to call that a transfer is going to create more confusion.

**Comment by diminator** [comment]
> The end-to-end transaction is a payment in my opinion.

I wonder if non-currency fungible asset transfers are also called payments? Probably they do, since you can pay with gold or any other token. However I feel like the general perception of the masses imply that it's either fiat or cryptocurrency. The term payments doesn't really fit well when trading shares or other assets. Then again, I am no fintec expert

It seems to me syntactically more correct and less biased to use 'transfers' opposed to 'payments'.

**Comment by adrianhopebailie** [comment]
> It seems to me syntactically more correct and less biased to use 'transfers' opposed to 'payments'.

I don't like calling a transaction that consists of multiple transfers, a transfer. 
Based on the definition of payment on Investopedia I am strngly supporting the continued use of "payment" 

>"A payment is the transfer of one form of good, service or financial asset in exchange for another form of good, service or financial asset in proportions that have been previously agreed upon by all parties involved. Payment can be made in the form of funds, assets or services."

http://www.investopedia.com/terms/p/payment.asp

**Comment by diminator** [comment]
That definition indeed covers the load of assets, currency, shares...

At BigchainDB, we always describe a local transfer as _transfer of ownership_ of a digital asset (currency, document, license, share, title and so on), which kinda makes sense from a document store point of view. The document/payload would remain the same but the ownership would change. Now if you want to exchange an asset type for another (interledger transfer), then I agree that the term payment would be well suited.

**Comment by clark800** [comment]
@emschwartz Yeah, "payment" isn't quite right because donations and transfers between accounts owned by one party do not fall under the definition of payments, but they are examples of interledger transfers. So I think you can say that it is "technically wrong" and we should fix it.

The financial term for a transfer on a single ledger is a "book transfer": http://www.investopedia.com/terms/b/book-transfer.asp

I'm not aware of an established term for a non-book transfer, but "interledger transfer" sounds good.
