### ISSUE TITLE
Add STREAM Receipts

### ISSUE THREAD

**Issue by sharafian** [interledger/rfcs#568]
This is something we've been talking about at Coil as a solution to make payment verification easier. Looking for feedback especially from those maintaining STREAM implementations or working on Web Monetization use cases

This proposal is meant to supercede the [Open Payments features of Sources](https://github.com/adrianhopebailie/open-payments/issues/19)

CC @adrianhopebailie @wilsonianb @kincaidoneil @matdehaast @sentientwaffle 

------

# STREAM Receipts

## Motivation

We've been discussing how to make payment verification on Interledger easy. This is immediately important for Web Monetization, where ILP payments must be verified to securely serve exclusive content. It also enables a host of other use cases including Codius and API micropayments.

Recently we've moved from a service that forwards ILP packets and signs JWTs that serve as proof of payment (https://github.com/sharafian/web-monetization-access) to a resource type in Open Payments (https://github.com/adrianhopebailie/open-payments/issues/19), and now we're exploring the idea of doing this receipt functionality at the STREAM layer.

## How would this work?

First, I want to define the different parties involved:

### Terminology

- **Receiver** - the party (probably a wallet) that is receiving funds over STREAM.
- **Verifier** - the party (for example a web monetized site's backend) that wishes to verify that ILP payments occurred to the receiver.
- **Sender** - the party that is sending funds over STREAM.

- **Receipt Nonce** - A random nonce used to identify a STREAM connection in receipts.
- **Receipt Seed** - An HMAC key known only to the verifier used to generate Receipt Secret.
- **Receipt Secret** - The key used to generate a Receipt's HMAC.
- **Receipt** - A binary object containing an integer amount of funds received on a stream, the Receipt Nonce for its STREAM connection, a Stream ID on the STREAM connection, a timestamp referring to the time that the stream was established, and an HMAC over all those fields.

### Flow

_This flow occurs for each STREAM connection with Receipts enabled._

First, the Verifier generates a random Receipt Nonce, and HMACs it with its Receipt Seed to create a Receipt Secret. This ensures the Receipt Secret will be unique to this STREAM connection.

The Verifier communicates the Receipt Secret and Receipt Nonce to the Receiver over some channel (see the SPSP section for an example). It's important that the Receipt Secret is shared between the Verifier and the Receiver, but not with the Sender. 

Before a STREAM connection is established, the Receipt Secret and Receipt Nonce are used as parameters to generate connection details (destinationAddress & sharedSecret). The Receipt Secret can be encrypted and encoded in the destinationAddress to allow the STREAM receiver to avoid persisting state. The Receipt Nonce can be included in the destinationAddress in cleartext to allow the STREAM receiver to avoid persisting state. The Receipt Nonce can be considered public, but must be unique each time STREAM parameters are generated.

Once the connection is open and the Sender is sending, the Receiver adds an additional frame to each of their ILP fulfills, containing a Receipt.

Each Receipt on a stream contains a progressively higher amount, representing the total amount received on that stream. So the latest Receipt on a stream replaces any previous Receipt on that stream. The timestamp in the receipt stays the same, as it represents the time the stream was established.

When the Verifier wishes to verify a Receipt, they parse out the Receipt Nonce. The Receipt Nonce is HMAC'ed with the Receipt Seed to regenerate the Receipt Secret statelessly. The Receipt Secret is used to verify the Receipt.

#### Keeping a Balance

The Sender can send these Receipts to the Verifier.

If the Verifier wants to keep a balance of how much the Sender paid, they should store the Receipt amount under the Receipt's Nonce + Receipt's Stream Id.

If there's already an amount under that stream ID then they credit the sender the difference in Receipt amounts.

If there isn't already an amount under that Nonce + stream ID, they have to make sure the Receipt timestamp isn't too long ago. If it's too long ago they may have already expired that row and it isn't safe to credit the sender that amount as they may be credited too much.

#### Not Keeping a Balance

For use cases where you care that the Sender paid but not how much, the Verifier can simply verify that the Receipt submitted from the Sender is recent. It only needs to look at the timestamp, so this scheme requires no persistence on the Verifier's part.

#### In SPSP

<img width="644" alt="Screen Shot 2020-02-06 at 10 08 37 AM" src="https://user-images.githubusercontent.com/3362563/73965439-0358d080-48c9-11ea-9426-bf6fc2ce67d5.png">

_flow diagram can be viewed [here](https://wilsonianb.github.io/diagrams/receipts.html) also_

In SPSP, the Sender would query the Verifier instead of the Receiver to look up SPSP params (basically the Verifier replaces the Receiver's URL with one of its own).

The Verifier then passees the SPSP query along to the receiver, but attaches two headers: `Receipt-Secret` and `Receipt-Nonce`. This is how the Receipt Secret & Receipt Nonce are shared between the Verifier and the Receiver. The Receiver uses the Receipt Secret and Receipt Nonce when generating the STREAM details. The Verifier passes the SPSP details (destinationAddress and sharedSecret) back from the Receiver to the Sender.

Other than this, SPSP doesn't require any changes.

#### Web Monetization

In addition to the above SPSP changes, Web Monetization could expose the receipt for each micropayment via the `monetizationprogress` event. This would let the webpage pass these receipts onto the site's backend, which would be behaving as the Verifier.

## How is this better than other approaches?

- 3rd party verification is simple: Even though we're using symmetric crypto, it's very easy to verify a receipt as a third party. So long as the Verifier can step into the middle of the setup flow (proxying the SPSP query for instance), they can establish a shared secret between themselves and the receiving wallet.

- No persistent state for Receiver: Receipts are not stored persistently and they only rely on the state of open streams, which can be ephemeral. That means Receivers using receipts don't need to worry about sessions/sources filling up their database or making this data available for later lookup.

- Puts common functionality into the transport: Because receipts are so broadly applicable, it makes sense to include it in the transport layer. That way many different application layer protocols can use it, not just those using SPSP/Open Payments.

- Less work for the wallet: Encapsulating this functionality in the STREAM protocol makes it so that wallets don't need to expose more API endpoints. Current wallets that implement SPSP functionality need only to handle two more headers and pull in a STREAM update.

- Uses only symmetric cryptography: by relying on HMAC as our signature scheme, we are able to avoid concerns like performance and PKI that would apply if we were using asymmetric crypto for the Receipt signatures

## Flaws

- If a Sender and Receiver collude, they can fool the Verifier. This is unlikely to be a real problem, because in most cases forging a Receipt only hurts the Receiver, not the Verifier. However it's important for Verifiers to know that Receipts cannot be counted as true unless they trust the Receiver.

- STREAM receivers MUST keep some ephemeral state to support Receipts. This isn't a problem in the JS implementation where the STREAM server tracks the amount received on a given stream for its lifetime, but as I understand it the Rust implementation does not keep even ephemeral state about open connections/streams. To support this feature the Rust implementation would likely need to lean on a cache for a sharded STREAM server to keep running totals on.

- By proxying the SPSP query, the Verifier is in control of where funds go. We think this is acceptable because in most cases the Verifier is already in control of this (if the Verifier is a Web Monetized site for instance, they can already choose what payment pointer goes in the page). You could build solutions around SPSP for ensuring that a given destination address belongs to some payment pointer, but we don't want to add the complication for the time being.

**Comment by wilsonianb** [comment]
>STREAM receivers MUST keep some ephemeral state to support Receipts. 

Could stateless receivers be supported by allowing an optional packet sequence number on the receipt?

Stateful receivers would exclude the packet sequence indicating that the amount is for the entire stream, and the amount would be tracked by Receipt's Nonce + Receipt's Stream Id (as described in the issue).

Stateless receivers would include the packet sequence indicating that the amount is standalone, which would be tracked by Receipt's Nonce + Receipt's Stream Id + Receipt's Packet Sequence.

**Comment by kincaidoneil** [comment]
Some questions I have:

- If the amount is in the destination asset, how does the verifier know the the recipient's asset details? Is this important?
- In the receipt model, once the payment reaches the verifier's threshold to provide the content, the sender will continue sending, paying out more than they need to. Is this a problem versus if the website controlled the STREAM sender?

The verifier seems to cede some control to the recipient. For Cinnamon, why would they want to cede control to the creator whether content is served or not? A clever receiver could return 0 amount receipts or receipts that very slowly increment (for no benefit to them, yes) but still at no cost to them and hurting the experience for Cinnamon & the site's visitor (they'd lie that the received less than they actually did).

In the model in which Cinnamon controls the STREAM sender, the trust model is flipped: each creator must trust Cinnamon, rather than Cinnamon trusting each creator. I think this is a safer model, since the platform has more reputation at stake than any individual creator.

Alternatively, we could use asymmetric crypto so the receipt is also verifiable by the STREAM sender. I don't think any PKI is required, since the private key could be seeded from the connection tag in the destination address, and the public key could be returned in the SPSP response.

> Could stateless receivers be supported by allowing an optional packet sequence number on the receipt?

That's an interesting idea. But it'd still be nice to have a single receipt to provide to a verifier, rather than one for every packet.

I think there's a way to do it: if we use public-key crypto and sign the sequence number, the sender could handle storing all the receipt state. On each packet, they would also send the receipt with the greatest sequence number. The recipient would verify they signed that receipt, and if it had one lower sequence number than the sequence number in that packet, they would add the amount and sign a new total receipt. If the receipt was a sequence number two or more packets earlier, the recipient would instead sign a per-packet receipt for only the amount in that packet (this is necessary to support multiple packets in flight). Then, the sender could periodically aggregate the receipts by sending the total receipt with one or more partial receipts. As long as the recipient is given all the receipts they previously signed with the sequence numbers in order, they can safely sign a new total receipt for a particular sequence number.

As Ben noted, this does add a lot of complexity and probably a minor performance hit (although WASM-based crypto proved to be plenty fast for us when we benchmarked it).

**Comment by wilsonianb** [comment]
:point_up_2: I opened a couple draft pr's for reference.

>how does the verifier know the the recipient's asset details?

Assuming the verifier is proxying SPSP queries, they already need to know the recient's payment pointer. The asset details could be provided to the verifier along with the payment pointer at initial setup, or perhaps open payments could allow the verifier to discover the asset details via the payment pointer.

>In the receipt model, once the payment reaches the verifier's threshold to provide the content, the sender will continue sending, paying out more than they need to. Is this a problem versus if the website controlled the STREAM sender?

Pooling paid amounts at the verifier by sender or WM provider for use in future web sessions would make it less of a problem.

>For e.g. Cinnamon, why would they want to cede control to the creator whether content is served or not?

I'm thinking it should be up to the sender to identify when a receiver is sending inaccurate receipts, since they're the only one able to check the veracity of receipts. The sender could immediately stop paying if it gets an erroneous receipt. With WM, the provider could then notifier the user that there's a problem with that recipient/creator?

**Comment by sharafian** [comment]
>  how does the verifier know the the recipient's asset details?

Like Brandon said, the verified knows the payment pointer and they can do some things with that. Probing the receiver via STREAM to discover exchange rate is one option, although it requires an ILP uplink. One could also cache rates for common currencies

>  In the model in which Cinnamon controls the STREAM sender, the trust model is flipped: each creator must trust Cinnamon, rather than Cinnamon trusting each creator. I think this is a safer model, since the platform has more reputation at stake than any individual creator.

This model where the site is a STREAM proxy is still available, it's just more infrastructure heavy. Running ILP infra yourself will provide the maximum amount of flexibility, but the hope with receipts is to provide simplicity while maintaining as much flexibility as possible.

> A clever receiver could return 0 amount receipts or receipts that very slowly increment (for no benefit to them, yes) but still at no cost to them and hurting the experience for Cinnamon & the site's visitor (they'd lie that the received less than they actually did).

Agreed that this is a major concern with payment pointers, because users are basically putting something dynamic directly into the page (comparable to image hotlinks). It may be that it's just not safe to have fully untrusted payment pointers, or it may be we find some sensible mitigations that can distinguish a misbehaving pointer from a visitor who isn't paying.

All that said, there's a wealth of situations where payment pointers are trusted to some extent. I imagine in most of the cases the receiver and verifier will have the same stakeholder (i.e. receiver is my wallet and verifier is my site). In these cases having the functionality for the verifier to verify payments to the receiver with minimal setup is highly advantageous.

So on the whole I think receipts can provide a valuable middle ground between the easily-bypassed client-side events and the infrastructure-heavy STREAM proxy approach.

> As Ben noted, this does add a lot of complexity and probably a minor performance hit (although WASM-based crypto proved to be plenty fast for us when we benchmarked it).

I think a sender would be mostly ok with the overhead from asymmetric crypto, but on the receiver side signing a receipt every packet when there are potentially thousands of packets per second can really add up when you're doing asymmetric crypto.

Right now the STREAM protocol that the receiver can keep state around the status of connections, though, and so I feel that leveraging that to make receipts less complex is fine. And even for the STREAM implementations that don't keep state in the process I don't think it's too big a lift to put state in some kind of memory cache.

I'm heavily biased towards keeping as much complexity away from the crypto side as possible

**Comment by sappenin** [comment]
Closed via https://github.com/interledger/rfcs/pull/570
