### ISSUE TITLE
RFC-3: What does a connector do if they receive a transfer where the conditions in the transfer frame and the ILP packet are different?

### ISSUE THREAD

**Issue by adrianhopebailie** [interledger/rfcs#74]
The connector wants to get the money on hold for them so they want the transfer frame condition to be fulfilled therefor they would use that condition unless there is another way to get it fulfilled (perhaps the fulfillment in the ILP Packet is used to generate the fulfillment in the transfer frame).

BUT what really matters is which condition the receiver will fulfill (See #73) because that is the fulfillment they are most likely to receive. This means using the condition in the transfer frame too.

All of this implies that a connector will only put a different condition in the transfer frame to the one in the ILP Packet if they are certain that another connector down the line (or the receiver) will:
a) Fulfill that condition or do something that fulfills it
b) put the original ILP Packet condition back into the transfer frame for their next hop so that the receiver fulfills that condition

We should have language in the spec that details these scenarios and provides normative language for expected behavior.

We don't need to spell out atomic mode but should lay the foundations

**Comment by justmoon** [comment]
Just to put a strawman out there:

The connector SHOULD reject the incoming transfer with an error "condition mismatch".

The logic behind this: The condition in the packet indicates that the final transfer should have that condition. If the condition in the transfer doesn't match that and the connector doesn't understand the relationship between the two conditions, then it should assume that the transfer is bugged and won't succeed if forwarded.

And we use "SHOULD" instead of "MUST", because the connector might know something we don't and may have a better course of action because of it.

I could be convinced to advocate a different default behavior if someone can come up with a strong use case for a legitimate situation where the conditions would be different.

**Comment by adrianhopebailie** [comment]
Building on what @justmoon has said above:

_If a connector detects that the condition for an incoming transfer does not match the condition in the ILP packet carried with that transfer, the connector SHOULD reject the incoming transfer with an error "condition mismatch". However, if the connector supports this scenario it MAY use either the condition from the incoming transfer or the condition from the ILP packet in a new outgoing transfer._

**Comment by emschwartz** [comment]
It would be important to note the danger a connector faces if it forwards the transfer using anything but the condition that was on the source transfer.

Along the lines of my general stance of "don't give people the tools to shoot themselves in the foot if you can avoid it", I think this is a pretty good argument for taking the condition out of the ILP packet. Yesterday when talking with @justmoon I started coming around to the idea of taking it out again.

I realized that if the condition is in the packet, the sender will need to extract it in order to attach it to the transfer, the connectors should ignore it, and the receiver will need to remove it to hash and regenerate the condition from the ILP packet. This means that no one really wants it in there.

**Comment by adrianhopebailie** [comment]
I agree with not having it in the packet however we should think carefully about the attacks that this may enable.

This would further enforce the analogue with IP too because the condition is really part of the layer in the stack below ILP, the ledger layer (Conditions/fulfillments are only ever evaluated by the ledgers and the end-points).

This also explains why the natural place for the condition is in the ledger transfer frame (i.e. the ledger specific wrapper around the ILP packet).

**Comment by emschwartz** [comment]
👍 

> I agree with not having it in the packet however we should think carefully about the attacks that this may enable.

Such as? Seems like there's less to attack there if it comes from the transfer. This assumes that you have to perfectly understand the differences in how ledgers might interpret or expect crypto conditions, and know when two from different ledgers are equivalent, but that was already a must for connectors.

**Comment by adrianhopebailie** [comment]
> Such as?

Currently it's possible to at least see if the transfer frame condition is different to the ILP packet condition but I guess it's also easy to spoof the packet so perhaps this changes nothing.

**Comment by emschwartz** [comment]
Correct. That's why it's useful to use a [Packet Scheme](https://github.com/interledger/rfcs/issues/66#issuecomment-238495443) that includes a hash of the ILP header/packet in the condition so it can be used as an integrity check.

**Comment by adrianhopebailie** [comment]
Conclusion is to not include condition in the packet
