### ISSUE TITLE
PROPOSAL: Map ILP Addresses to existing accounts on existing networks

### ISSUE THREAD

**Issue by adrianhopebailie** [interledger/rfcs#81]
The Interledger Protocol defines a universal addressing scheme for any digital asset account. In order to transfer assets into existing accounts it is necessary to address these accounts.

To bootstrap this network this document proposes ILP addressing schemes for a number of existing payment networks so that connectors offering delivery into those networks can provide consistent routing information.

> _**Note:**_ This list is intended to seed a discussion. If there is interesting in building out this list it's probably a good candidate for a new RFC.
# Mappings

The mappings below are proposed as ILP addresses for existing digital asset accounts:

| Network | Address Format | Example | Notes |
| --- | --- | --- | --- |
| Bitcoin | `bitcoin.<address>` | `bitcoin.145b3dEskk1a7Uw4gWBdpa8NFEwbfz2MgT` |  |
| Global Banks | `iban.<iban>` | `iban.IE64BOFI90583812345678` |  |
| Global Banks | `bic.<bic>.<account_identifier>` | `bic.BOFIIE2D.12345678` |  |
| Any card network | `pan.<card_pan>` | `pan.5432376523489763` |  |
| Paypal | `paypal.email.<email_address>` | `paypal.email.sombeody@example.com` | `@` is not currently supported in ILP addresses |
| Paypal | `paypal.phone.<int_phone_number>` | `paypal.phone.19995550123` | The `+` prefix is dropped from the number |

**Comment by justmoon** [comment]
We may want to include a segment for the type of ledger plugin being used, since they may not be mutually compatible. E.g. `bitcoin.acme.v1.<address>` for Acme's v1 Bitcoin ledger plugin. It makes sense for them to share a prefix since it is still the same underlying ledger, so it would be possible to provide liquidity between different plugin versions cheaply since there is no FX risk.

Regarding `iban`/`bic` - if we're going to have these, it might be good to choose one or the other. Note that addresses should ideally be chosen based on proximity in the routing graph. (The only point of having ILP addresses to begin with - as opposed to UUIDs for example - is to eliminate routing table redundancies by combining entries with the same prefixes.)

Note that the IBAN also mixes account and ledger information, so it may not be a good identifier to use. BICs also identify banks, not ledgers. (One bank may have many ledgers, e.g. different currencies.)

I don't think it makes sense to have a single RFC for address translation. Address translation depends heavily on the ledger in question, so whichever RFC specifies the ledger layer should also decide address translation for that ledger. We may want to have an RFC that gives some guidelines to ledger spec editors, but it might be good to gain more experience first.

**Comment by adrianhopebailie** [comment]
> We may want to include a segment for the type of ledger plugin being used, since they may not be mutually compatible.

I don't understand this. If I am sending to someone why would I need to know what type of ledger they have?

I can understand there being alternative addresses for the same account which, by their prefix, force the payment to go via a specific connector but surely anyone that can deliver to a Bitcoin address can advertise that they can handle the route `bitcoin.`?

> Regarding iban/bic - if we're going to have these, it might be good to choose one or the other. 

I'm not sure if all bank accounts are allocated IBANs which is why I had the BIC based prefix as an alternate (fallback)

> Note that the IBAN also mixes account and ledger information, so it may not be a good identifier to use.

Maybe we can pull the country code out into the ledger/network prefix so the IBAN `IE64BOFI90583812345678` is addressed as `iban.ie.IE64BOFI90583812345678`. 

Here the ledger/network is "the Irish banking network". So the ILP transfer would terminate at the connector that is able to deliver to any account in Ireland. After that it's like packet that has passed through gateway with NAT. The specifics of how the transfer gets to the end account is unknown.

I realize this is not as good as being able to build and address that is specific to the actual bank ledger but this is a pretty good bootstrapping intermediate step.

> BICs also identify banks, not ledgers. (One bank may have many ledgers, e.g. different currencies.)

As above, this is true but is it a problem? It's not as specific as it could be but it's probably still enough to do a transfer.

> Address translation depends heavily on the ledger in question, so whichever RFC specifies the ledger layer should also decide address translation for that ledger. 

The purpose of this is to bootstrap the existing system. There will be many ledgers that are simply not going to implement ILP soon but they may still be accessible to connectors that want to be able to do deliveries to that ledger via an existing payment network. This last-mile could be addressed with trustlines but is hard to do if that end account can't be addressed.

**Comment by adrianhopebailie** [comment]
Superseded by the new ILP Addresses spec: https://github.com/interledger/rfcs/blob/master/0015-ilp-addresses/0015-ilp-addresses.md
