### ISSUE TITLE
RFC-2: Deduplicate subfulfillments

### ISSUE THREAD

**Issue by justmoon** [interledger/rfcs#86]
The same subfulfillment may appear multiple times in a complex fulfillment. It could even appear on different levels of a fulfillment tree. We should have a way to deduplicate those occurrences, so that subfulfillments are only verified once and only appear once on the wire.

**Comment by diminator** [comment]
> We should have a way to deduplicate those occurrences

Agreed. 

There are multiple issues related. First one is the detection of duplicates:
I was working on a way to easily query subconditions based on a lambda function. eg. `theshold_fulfillment.get_subconditions(lamdba c: c.type == <TYPE_ID> && c.attribute == <VALUE>)`
This would return me a list of subconditions that fit the filter function.

Second one: It's probably a bad idea to prune them out, what about linking them?

**Comment by adrianhopebailie** [comment]
What is the underlying issue this would solve?

If it is simply space then perhaps we can simply replace the fulfillment with its condition everywhere except at the highest level is appears?

i.e. If a fulfillment appears in multiple places then replace all but one with the condition and say in the spec that this is allowed and that implementations should cache sub-fulfillments and their derived condition while validating a complex fulfillment and where possible substitute the fulfillment for the condition.

Will make validation quite complex!

**Comment by adrianhopebailie** [comment]
From call today, a new proposes structure for fulfillments :

```
CryptoCondition-Fulfillment ::= SEQUENCE {
  fulfillments SET OF Fulfillment,
  root Fulfillment
}

Fulfillment ::= CHOICE {
  preimage PreimageFulfillment ,
  prefix PrefixFulfillment,
  threshold ThresholdFulfillment,
  rsaSha256 RsaSha256Fulfillment,
  ed25519 Ed25519Fulfillment
}

PreimageFulfillment ::= OCTET STRING

PrefixFulfillment ::= SEQUENCE {
  prefix OCTET STRING,
  subcondition Condition
}

ThresholdFulfillment ::= SEQUENCE {
  threshold INTEGER (1..65535),
  subconditions SEQUENCE OF Condition
}

RsaSha256Fulfillment ::= SEQUENCE {
  publicKey RSAPublicKey,
  signature OCTET STRING
}

Ed25519Fulfillment ::= SEQUENCE {
  publicKey OCTET STRING (SIZE(32)),
  signature OCTET STRING (SIZE(64))
}

-- IMPORTS from [RFC8017]{#8017}
RSAPublicKey ::= SEQUENCE {
      modulus INTEGER,  -- n
      publicExponent INTEGER -- e
}
```

**Comment by stevenroose** [comment]
As mentioned in the call, this would no longer make subfulfillment verification obvious.

Instead of an interface like `fulfillment.validate(optional condition, nullable message)`, you would need a way for the fulfillment to reach the store of fulfillments at the top-level. Something like `fulfillment.validate(optional condition, nullable message, map(Fingerprint -> Fulfillment) subconditions)`.

**Comment by justmoon** [comment]
>``` asn1
>CryptoCondition-Fulfillment ::= SEQUENCE {
>  fulfillments SEQUENCE OF Fulfillment,
>  root Condition
>}
>
>Fulfillment ::= CHOICE {
>  preimage PreimageFulfillment ,
>  prefix PrefixFulfillment,
>  threshold ThresholdFulfillment,
>  rsaSha256 RsaSha256Fulfillment,
>  ed25519 Ed25519Fulfillment
>}
>```

I would rename some things here. Also if you have a separate `root` property, then the array can be a `SET OF`.

``` asn1
Fulfillment ::= SEQUENCE {
  root Condition,
  subfulfillments SET OF Subfulfillment
}

Subfulfillment ::= CHOICE {
  preimage PreimageSubfulfillment ,
  prefix PrefixSubfulfillment,
  threshold ThresholdSubfulfillment,
  rsaSha256 RsaSha256Subfulfillment,
  ed25519 Ed25519Subfulfillment
}
```

I'm not married to the term `Subfulfillment` although it feels mostly natural to me. But I do feel strongly that `Fulfillment` should be the top level thing. As Steven points out, it's not a complete fulfillment unless you also have the other subfulfillments:

> An interface like this is no longer possible
> ```
> fulfillment.validate(
>    optional condition, 
>    nullable message)
> ```

I think it's still possible if a "fulfillment" is defined to be the outer thing. That would mean that in implementations, the `Fulfillment` class contains a set of subfulfillments and a `root` pointer to one of them. If I call a.addSubfulfillment(b), it actually just joins the set `b.subfulfillments` to `a.subfulfillments`, that's it.

That turns out to be quite powerful. Right now (in the JavaScript implementation), suppose I have a `Fulfillment` object that represents some complex tree of conditions, none of which are presently fulfilled. Now I get some fulfillments and I'd like to use them to fulfill the appropriate subconditions in the tree. That's quite a complicated operation right now, because I need to find the right subconditions and then call `addSubfulfillment` on each of their parents. If a condition appears multiple times, I need to call `addSubfulfillment` once for each parent.

If we go with this new structure on the other hand, I just call `addSubfulfillment` on the root `Fulfillment` object and that's it. Much simpler.

**Comment by stevenroose** [comment]
I like how currently one condition corresponds to one fulfillment. Semantically that makes sense because the fulfillment fulfills the condition.

Intuitively, I'd call a pair of a condition and the fulfilling information (fulfillments of itself and its sub-conditions) a *`fulfilled condition`*.

That aside, your argument has nothing to do with the validation process. Current implementations (JS, Java and Go), process validation at the level of the Fulfillment itself, which means by using the information it contains, amongst which it's sub-fulfillments. The verification cannot be done in a different context because each fulfillment has its own way of verifying. 

Another thing I'm thinking about, fulfillments need their subfulfillment information in order to generate the condition object they are fulfilling. Which they need to do in order to compare it with the condition they try to verify.
